const themesData = [
  {
    id: 1,
    title: '1) 인사표현 & 호칭',
    icon: '👋',
    words: [
      // --- 인사 및 대명사 ---
      { ch: '你', py: 'nǐ', mean: '너' },
      { ch: '你们', py: 'nǐmen', mean: '너희들' },
      { ch: '您', py: 'nín', mean: '당신, 귀하 (존칭)' },
      { ch: '好', py: 'hǎo', mean: '좋다, 안녕하다' },
      { ch: '再见', py: 'zàijiàn', mean: '잘가, 또 만나' },
      { ch: '谢谢您', py: 'xièxie nín', mean: '(당신께) 감사합니다' },
      {
        ch: '感谢您对我的支持',
        py: 'gǎnxiè nín duì wǒ de zhīchí',
        mean: '당신의 지원에 감사드립니다',
      },
      { ch: '不客气', py: 'bú kèqi', mean: '천만에요, 별말씀을요' },
      { ch: '不用谢', py: 'búyòng xiè', mean: '감사할 필요 없어요' },
      { ch: '对不起', py: 'duìbuqǐ', mean: '죄송합니다, 미안합니다' },
      { ch: '不好意思', py: 'bùhǎoyìsi', mean: '미안합니다 (가벼운 사과)' },
      { ch: '抱歉', py: 'bàoqiàn', mean: '죄송합니다 (정중)' },
      { ch: '向您道歉', py: 'xiàng nín dàoqiàn', mean: '당신께 사과드립니다' },
      { ch: '没关系', py: 'méi guānxi', mean: '괜찮아요, 상관없어요' },
      { ch: '我', py: 'wǒ', mean: '나, 저' },
      { ch: '我们', py: 'wǒmen', mean: '우리' },
      { ch: '咱们', py: 'zánmen', mean: '우리 (청자 포함)' },
      { ch: '他', py: 'tā', mean: '그 (남자)' },
      { ch: '她', py: 'tā', mean: '그녀' },
      { ch: '大家', py: 'dàjiā', mean: '여러분, 모두' },
      { ch: '喂', py: 'wéi', mean: '여보세요 (전화)' },
      { ch: '它', py: 'tā', mean: '그것 (사물/동물)' },
      { ch: '别人', py: 'biérén', mean: '남, 타인' },
      { ch: '这儿', py: 'zhèr', mean: '여기' },
      { ch: '那儿', py: 'nàr', mean: '거기, 저기' },
      { ch: '哪儿', py: 'nǎr', mean: '어디' },

      // --- 가족 및 호칭 ---
      { ch: '妈妈', py: 'māma', mean: '엄마' },
      { ch: '爸爸', py: 'bàba', mean: '아빠' },
      { ch: '爷爷', py: 'yéye', mean: '할아버지' },
      { ch: '奶奶', py: 'nǎinai', mean: '할머니' },
      { ch: '外公', py: 'wàigōng', mean: '외할아버지' },
      { ch: '外婆', py: 'wàipó', mean: '외할머니' },
      { ch: '姐姐', py: 'jiějie', mean: '언니, 누나' },
      { ch: '哥哥', py: 'gēge', mean: '오빠, 형' },
      { ch: '妹妹', py: 'mèimei', mean: '여동생' },
      { ch: '弟弟', py: 'dìdi', mean: '남동생' },
      { ch: '儿子', py: 'érzi', mean: '아들' },
      { ch: '女儿', py: "nǚ'ér", mean: '딸' },
      { ch: '妻子', py: 'qīzi', mean: '아내' },
      { ch: '老婆', py: 'lǎopo', mean: '마누라, 여보 (아내 호칭)' },
      { ch: '丈夫', py: 'zhàngfu', mean: '남편' },
      { ch: '老公', py: 'lǎogōng', mean: '남편 (호칭)' },
      { ch: '叔叔', py: 'shūshu', mean: '삼촌, 아저씨' },
      { ch: '阿姨', py: 'āyí', mean: '이모, 아주머니' },
      { ch: '孙子', py: 'sūnzi', mean: '손자' },
      { ch: '亲戚', py: 'qīnqi', mean: '친척' },
      { ch: '表哥', py: 'biǎogē', mean: '사촌 형/오빠' },
    ],
  },
  {
    id: 2,
    title: '2) 쇼핑하기',
    icon: '🛍️',
    words: [
      // --- 동사 ---
      { ch: '穿', py: 'chuān', mean: '입다, 신다' },
      { ch: '戴', py: 'dài', mean: '쓰다, 착용하다 (액세서리)' },
      { ch: '带', py: 'dài', mean: '지니다, 챙기다' },
      { ch: '拿', py: 'ná', mean: '들다, 잡다' },
      { ch: '选择', py: 'xuǎnzé', mean: '선택하다, 고르다' },

      // --- 의류 & 잡화 ---
      { ch: '皮鞋', py: 'píxié', mean: '구두' },
      { ch: '皮包', py: 'píbāo', mean: '가죽 가방' },
      { ch: '钱包', py: 'qiánbāo', mean: '지갑' },
      { ch: '衣服', py: 'yīfu', mean: '옷' },
      { ch: '大衣', py: 'dàyī', mean: '외투, 코트' },
      { ch: '西服', py: 'xīfú', mean: '양복' },
      { ch: '领带', py: 'lǐngdài', mean: '넥타이' },
      { ch: '衬衫', py: 'chènshān', mean: '셔츠, 블라우스' },
      { ch: '裙子', py: 'qúnzi', mean: '치마' },
      { ch: '裤子', py: 'kùzi', mean: '바지' },
      { ch: '牛仔裤', py: 'niúzǎikù', mean: '청바지' },
      { ch: '袜子', py: 'wàzi', mean: '양말' },
      { ch: '手套', py: 'shǒutào', mean: '장갑' },
      { ch: '手表', py: 'shǒubiǎo', mean: '손목시계' },
      { ch: '帽子', py: 'màozi', mean: '모자' },
      { ch: '项链', py: 'xiàngliàn', mean: '목걸이' },
      { ch: '戒指', py: 'jièzhi', mean: '반지' },

      // --- 전자제품 ---
      { ch: '手机', py: 'shǒujī', mean: '휴대폰' },
      { ch: '智能手机', py: 'zhìnéng shǒujī', mean: '스마트폰' },
      { ch: 'U盘', py: 'U pán', mean: 'USB 메모리' },
      { ch: '移动硬盘', py: 'yídòng yìngpán', mean: '외장 하드' },
      { ch: '冰箱', py: 'bīngxiāng', mean: '냉장고' },
      { ch: '电视', py: 'diànshì', mean: 'TV, 텔레비전' },
      { ch: '电脑', py: 'diànnǎo', mean: '컴퓨터' },
      { ch: '空调', py: 'kōngtiáo', mean: '에어컨' },

      // --- 색상 ---
      { ch: '颜色', py: 'yánsè', mean: '색깔' },
      { ch: '红色', py: 'hóngsè', mean: '빨간색' },
      { ch: '粉色', py: 'fěnsè', mean: '분홍색' },
      { ch: '橘色', py: 'júsè', mean: '주황색' },
      { ch: '黄色', py: 'huángsè', mean: '노란색' },
      { ch: '黑色', py: 'hēisè', mean: '검은색' },
      { ch: '灰色', py: 'huīsè', mean: '회색' },
      { ch: '蓝色', py: 'lánsè', mean: '파란색' },
      { ch: '天蓝色', py: 'tiānlánsè', mean: '하늘색' },
      { ch: '绿色', py: 'lǜsè', mean: '초록색' },

      // --- 상태/형용사 ---
      { ch: '合适', py: 'héshì', mean: '적합하다, 알맞다' },
      { ch: '适合', py: 'shìhé', mean: '~에 어울리다' },
      { ch: '便宜', py: 'piányi', mean: '싸다' },
      { ch: '贵', py: 'guì', mean: '비싸다' },
      { ch: '漂亮', py: 'piàoliang', mean: '예쁘다' },
      { ch: '美丽', py: 'měilì', mean: '아름답다' },
      { ch: '假', py: 'jiǎ', mean: '가짜의' },
      { ch: '真', py: 'zhēn', mean: '진짜, 정말' },
      { ch: '很', py: 'hěn', mean: '매우, 아주' },
      { ch: '怎么样', py: 'zěnmeyàng', mean: '어때요? (상태)' },

      // --- 양사 및 기타 ---
      { ch: '条', py: 'tiáo', mean: '(양사) 긴 것, 바지/치마' },
      { ch: '件', py: 'jiàn', mean: '(양사) 옷, 사건' },
      { ch: '双', py: 'shuāng', mean: '(양사) 켤레, 쌍' },
      { ch: '都', py: 'dōu', mean: '모두, 다' },
      { ch: '不', py: 'bù', mean: '~아니다 (부정)' },
      { ch: '的', py: 'de', mean: '~의, ~한 것' },
      { ch: '吗', py: 'ma', mean: '~입니까? (의문)' },
      { ch: '什么', py: 'shénme', mean: '무엇' },
      { ch: '谁', py: 'shéi', mean: '누구' },
      { ch: '想', py: 'xiǎng', mean: '~하고 싶다' },
    ],
  },
  {
    id: 3,
    title: '3) 시간 말하기',
    icon: '⏰',
    words: [
      // --- 하루의 시간대 ---
      { ch: '早上', py: 'zǎoshang', mean: '아침' },
      { ch: '早晨', py: 'zǎochen', mean: '이른 아침, 새벽' },
      { ch: '上午', py: 'shàngwǔ', mean: '오전' },
      { ch: '中午', py: 'zhōngwǔ', mean: '점심, 정오' },
      { ch: '下午', py: 'xiàwǔ', mean: '오후' },
      { ch: '晚上', py: 'wǎnshang', mean: '저녁, 밤' },
      { ch: '深夜', py: 'shēnyè', mean: '심야, 한밤중' },
      { ch: '现在', py: 'xiànzài', mean: '지금, 현재' },

      // --- 날짜 표현 ---
      { ch: '今天', py: 'jīntiān', mean: '오늘' },
      { ch: '昨天', py: 'zuótiān', mean: '어제' },
      { ch: '前天', py: 'qiántiān', mean: '그저께' },
      { ch: '明天', py: 'míngtiān', mean: '내일' },
      { ch: '后天', py: 'hòutiān', mean: '모레' },
      { ch: '最近', py: 'zuìjìn', mean: '요즘, 최근' },

      // --- 시간 단위 ---
      { ch: '点', py: 'diǎn', mean: '시 (시각)' },
      { ch: '分', py: 'fēn', mean: '분 (시각)' },
      { ch: '秒', py: 'miǎo', mean: '초' },
      { ch: '刻', py: 'kè', mean: '15분' },
      { ch: '半', py: 'bàn', mean: '반, 30분' },
      { ch: '小时', py: 'xiǎoshí', mean: '시간 (동안)' },
      { ch: '分钟', py: 'fēnzhōng', mean: '분 (동안)' },
      { ch: '几', py: 'jǐ', mean: '몇 (수량/시간)' },

      // --- 숫자 (1~10) ---
      { ch: '一', py: 'yī', mean: '1, 하나' },
      { ch: '二', py: 'èr', mean: '2, 둘' },
      { ch: '两', py: 'liǎng', mean: '둘 (개수/시간)' },
      { ch: '三', py: 'sān', mean: '3, 셋' },
      { ch: '四', py: 'sì', mean: '4, 넷' },
      { ch: '五', py: 'wǔ', mean: '5, 다섯' },
      { ch: '六', py: 'liù', mean: '6, 여섯' },
      { ch: '七', py: 'qī', mean: '7, 일곱' },
      { ch: '八', py: 'bā', mean: '8, 여덟' },
      { ch: '九', py: 'jiǔ', mean: '9, 아홉' },
      { ch: '十', py: 'shí', mean: '10, 열' },

      // --- 주/월/년 ---
      { ch: '星期', py: 'xīngqī', mean: '요일, 주' },
      { ch: '周末', py: 'zhōumò', mean: '주말' },
      { ch: '礼拜天', py: 'lǐbàitiān', mean: '일요일' },
      { ch: '月', py: 'yuè', mean: '월, 달' },
      { ch: '号', py: 'hào', mean: '일 (날짜)' },
      { ch: '日', py: 'rì', mean: '날, 일' },
      { ch: '年', py: 'nián', mean: '년, 해' },
      { ch: '今年', py: 'jīnnián', mean: '올해' },
      { ch: '去年', py: 'qùnián', mean: '작년' },
      { ch: '明年', py: 'míngnián', mean: '내년' },

      // --- 기간 및 기타 ---
      { ch: '未来', py: 'wèilái', mean: '미래' },
      { ch: '淡季', py: 'dànjì', mean: '비수기' },
      { ch: '旺季', py: 'wàngjì', mean: '성수기' },
      { ch: '黄金周', py: 'huángjīnzhōu', mean: '황금주간 (연휴)' },
      { ch: '时间', py: 'shíjiān', mean: '시간' },
      { ch: '的时候', py: 'de shíhou', mean: '~할 때' },
      { ch: '高峰期', py: 'gāofēngqī', mean: '러시아워, 혼잡 시간' },
    ],
  },

  {
    id: 4,
    title: '4) 교통수단 이용하기',
    icon: '🚌',
    words: [
      // --- 동작 (타다/운전하다) ---
      { ch: '开', py: 'kāi', mean: '운전하다, 열다' },
      { ch: '坐', py: 'zuò', mean: '(교통수단을) 타다, 앉다' },
      { ch: '换乘', py: 'huànchéng', mean: '갈아타다, 환승하다' },
      { ch: '骑', py: 'qí', mean: '(자전거/동물을) 타다' },
      { ch: '出发', py: 'chūfā', mean: '출발하다' },
      { ch: '到', py: 'dào', mean: '도착하다' },
      { ch: '开始', py: 'kāishǐ', mean: '시작하다' },
      { ch: '发生', py: 'fāshēng', mean: '발생하다, 생기다' },
      { ch: '注意', py: 'zhùyì', mean: '조심하다, 주의하다' },

      // --- 교통수단 ---
      { ch: '出租车', py: 'chūzūchē', mean: '택시' },
      { ch: '汽车', py: 'qìchē', mean: '자동차' },
      { ch: '船', py: 'chuán', mean: '배' },
      { ch: '公共汽车', py: 'gōnggòngqìchē', mean: '버스' },
      { ch: '长途汽车', py: 'chángtú qìchē', mean: '시외버스' },
      { ch: '地铁', py: 'dìtiě', mean: '지하철' },
      { ch: '自行车', py: 'zìxíngchē', mean: '자전거' },
      { ch: '摩托车', py: 'mótuōchē', mean: '오토바이' },

      // --- 장소 및 관련 명사 ---
      { ch: '站', py: 'zhàn', mean: '역, 정류장' },
      { ch: '交通', py: 'jiāotōng', mean: '교통' },
      { ch: '高速公路', py: 'gāosù gōnglù', mean: '고속도로' },
      { ch: '售票处', py: 'shòupiàochù', mean: '매표소' },
      { ch: '车费', py: 'chēpiào', mean: '차비' },
      { ch: '车票', py: 'chēpiào', mean: '차표, 승차권' },
      { ch: '地铁票', py: 'dìtiě piào', mean: '지하철표' },
      { ch: '司机', py: 'sījī', mean: '기사, 운전사' },
      { ch: '师傅', py: 'shīfu', mean: '기사님, 선생님 (호칭)' },

      // --- 상태 및 형용사 ---
      { ch: '堵车', py: 'dǔchē', mean: '차가 막히다' },
      { ch: '快', py: 'kuài', mean: '빠르다' },
      { ch: '慢', py: 'màn', mean: '느리다' },
      { ch: '安全', py: 'ānquán', mean: '안전하다' },
      { ch: '复杂', py: 'fùzá', mean: '복잡하다' },
      { ch: '马上', py: 'mǎshàng', mean: '곧, 즉시' },
      { ch: '一定', py: 'yídìng', mean: '반드시, 꼭' },

      // --- 자동차 브랜드 ---
      { ch: '奔驰', py: 'Bēnchí', mean: '벤츠' },
      { ch: '宝马', py: 'Bǎomǎ', mean: 'BMW' },
      { ch: '奥迪', py: 'Àodí', mean: '아우디' },
      { ch: '大众', py: 'Dàzhòng', mean: '폭스바겐' },
      { ch: '现代', py: 'Xiàndài', mean: '현대(자동차)' },
      { ch: '起亚', py: 'Qǐyà', mean: '기아(자동차)' },
      { ch: '三星', py: 'Sānxīng', mean: '삼성' },

      // --- 기타 ---
      { ch: '辆', py: 'liàng', mean: '(양사) 대 (차량 세는 단위)' },
      { ch: '趟', py: 'tàng', mean: '(양사) 번, 차례 (왕래 횟수)' },
      { ch: '比', py: 'bǐ', mean: '~보다 (비교)' },
      { ch: '没有', py: 'méiyǒu', mean: '없다, ~하지 않았다' },
      { ch: '行', py: 'xíng', mean: '좋다, 가능하다' },
      { ch: '或者', py: 'huòzhě', mean: '아니면, 또는' },
    ],
  },
  {
    id: 5,
    title: '5) 여행 준비 및 계획',
    icon: '✈️',
    words: [
      // --- 계획 및 방학 ---
      { ch: '打算', py: 'dǎsuàn', mean: '계획하다, ~할 작정이다' },
      { ch: '放暑假', py: 'fàng shǔjià', mean: '여름방학을 하다' },
      { ch: '寒假', py: 'hánjià', mean: '겨울방학' },
      { ch: '节日', py: 'jiérì', mean: '명절, 기념일' },
      { ch: '旅行', py: 'lǚxíng', mean: '여행하다' },
      { ch: '旅游', py: 'lǚyóu', mean: '관광하다, 여행하다' },
      { ch: '导游', py: 'dǎoyóu', mean: '관광 가이드' },

      // --- 준비물 ---
      { ch: '护照', py: 'hùzhào', mean: '여권' },
      { ch: '签证', py: 'qiānzhèng', mean: '비자' },
      { ch: '免签', py: 'miǎnqiān', mean: '비자 면제' },
      { ch: '手续费', py: 'shǒuxùfèi', mean: '수속비' },
      { ch: '行李箱', py: 'xínglǐxiāng', mean: '트렁크, 여행 가방' },
      { ch: '背包', py: 'bèibāo', mean: '배낭' },
      { ch: '地图', py: 'dìtú', mean: '지도' },
      { ch: '泳衣', py: 'yǒngyī', mean: '수영복' },
      { ch: '拖鞋', py: 'tuōxié', mean: '슬리퍼' },
      { ch: '洗漱用品', py: 'xǐshù yòngpǐn', mean: '세면도구' },
      { ch: '充电器', py: 'chōngdiànqì', mean: '충전기' },
      { ch: '移动电源', py: 'yídòng diànyuán', mean: '보조 배터리' },
      { ch: '转换插头', py: 'zhuănhuàn chātóu', mean: '멀티 플러그' },
      { ch: '必备', py: 'bìbèi', mean: '필수 구비하다' },
      { ch: '药品', py: 'yàopǐn', mean: '약품' },
      { ch: '纸巾', py: 'zhǐjīn', mean: '티슈, 휴지' },
      { ch: '睡衣', py: 'shuìyī', mean: '잠옷' },
      { ch: '旅行者保险', py: 'lǚxíngzhě bǎoxiǎn', mean: '여행자 보험' },
      { ch: '手机漫游', py: 'shǒujī mànyóu', mean: '휴대폰 로밍' },
      { ch: '换钱', py: 'huànqián', mean: '환전하다' },
      { ch: '汇率', py: 'huìlǜ', mean: '환율' },
      { ch: '清单', py: 'qīngdān', mean: '목록, 리스트' },

      // --- 공항 및 교통 ---
      { ch: '飞机', py: 'fēijī', mean: '비행기' },
      { ch: '机场', py: 'jīchǎng', mean: '공항' },
      { ch: '登机牌', py: 'dēngjīpái', mean: '탑승권' },
      { ch: '航班', py: 'hángbān', mean: '항공편' },
      { ch: '起飞', py: 'qǐfēi', mean: '이륙하다' },
      { ch: '降落', py: 'jiàngluò', mean: '착륙하다' },
      { ch: '经济舱', py: 'jīngjìcāng', mean: '이코노미석' },
      { ch: '商务舱', py: 'shāngwùcāng', mean: '비즈니스석' },
      { ch: '乘坐', py: 'chéngzuò', mean: '탑승하다, 타다' },
      { ch: '火车站', py: 'huǒchēzhàn', mean: '기차역' },
      { ch: '船', py: 'chuán', mean: '배, 선박' },
      { ch: '送', py: 'sòng', mean: '배웅하다' },
      { ch: '拉', py: 'lā', mean: '(가방을) 끌다, 당기다' },

      // --- 장소 및 관광지 ---
      { ch: '中国', py: 'Zhōngguó', mean: '중국' },
      { ch: '首都', py: 'shǒudū', mean: '수도' },
      { ch: '北京', py: 'Běijīng', mean: '베이징' },
      { ch: '长城', py: 'Chángchéng', mean: '만리장성' },
      { ch: '黄河', py: 'Huánghé', mean: '황허강' },
      { ch: '长江', py: 'Chángjiāng', mean: '양쯔강 (창강)' },
      { ch: '大使馆', py: 'dàshǐguǎn', mean: '대사관' },
      { ch: '饭店', py: 'fàndiàn', mean: '호텔, 식당' },
      { ch: '宾馆', py: 'bīnguǎn', mean: '호텔' },
      { ch: '世界', py: 'shìjiè', mean: '세계' },
      { ch: '国家', py: 'guójiā', mean: '국가' },
      { ch: '地方', py: 'dìfang', mean: '장소, 곳' },
      { ch: '文化', py: 'wénhuà', mean: '문화' },

      // --- 상태 및 문제상황 ---
      { ch: '迷路', py: 'mílù', mean: '길을 잃다' },
      { ch: '奇怪', py: 'qíguài', mean: '이상하다' },
      { ch: '方便', py: 'fāngbiàn', mean: '편리하다' },
      { ch: '国籍', py: 'guójí', mean: '국적' },
      { ch: '票', py: 'piào', mean: '표, 티켓' },
    ],
  },
  {
    id: 6,
    title: '6) 구매하기',
    icon: '🛒',
    words: [
      // --- 쇼핑 장소 및 수단 ---
      { ch: '购物', py: 'gòuwù', mean: '쇼핑, 물건을 사다' },
      { ch: '商店', py: 'shāngdiàn', mean: '상점' },
      { ch: '超市', py: 'chāoshì', mean: '슈퍼마켓' },
      { ch: '百货商店', py: 'bǎihuòshāngdiàn', mean: '백화점' },
      { ch: '购物中心', py: 'gòuwù zhōngxīn', mean: '대형 쇼핑센터' },
      { ch: '网上购物', py: 'wǎngshàng gòuwù', mean: '온라인 쇼핑' },
      { ch: '电视购物', py: 'diànshì gòuwù', mean: 'TV 홈쇼핑' },

      // --- 구매/판매 동작 ---
      { ch: '买', py: 'mǎi', mean: '사다, 구매하다' },
      { ch: '卖', py: 'mài', mean: '팔다, 판매하다' },
      { ch: '支付', py: 'zhīfù', mean: '지불하다' },
      { ch: '交换', py: 'jiāohuàn', mean: '교환하다' },
      { ch: '退款', py: 'tuìkuǎn', mean: '환불하다' },
      { ch: '退货', py: 'tuìhuò', mean: '반품하다' },
      { ch: '送货', py: 'sònghuò', mean: '배달하다' },
      { ch: '需要', py: 'xūyào', mean: '필요하다' },
      { ch: '换', py: 'huàn', mean: '바꾸다, 교환하다' },
      { ch: '赠送', py: 'zèngsòng', mean: '증정하다' },

      // --- 결제 및 물품 ---
      { ch: '东西', py: 'dōngxi', mean: '물건' },
      { ch: '纸币', py: 'zhǐbì', mean: '지폐' },
      { ch: '硬币', py: 'yìngbì', mean: '동전' },
      { ch: '发票', py: 'fāpiào', mean: '영수증' },
      { ch: '开票', py: 'kāipiào', mean: '영수증을 발급하다' },
      { ch: '优惠券', py: 'yōuhuìquàn', mean: '할인권' },
      { ch: '购物卡', py: 'gòuwùkǎ', mean: '쇼핑 카드' },
      { ch: '会员卡', py: 'huìyuánkǎ', mean: '멤버십 카드' },
      { ch: '积分', py: 'jīfēn', mean: '마일리지, 포인트' },
      { ch: '塑料袋', py: 'sùliàodài', mean: '비닐봉지' },
      { ch: '收银台', py: 'shōuyíntái', mean: '계산대' },
      { ch: '推车', py: 'tuīchē', mean: '쇼핑 카트' },
      { ch: '售货员', py: 'shòuhuòyuán', mean: '판매원' },

      // --- 과일 및 채소 ---
      { ch: '水果', py: 'shuǐguǒ', mean: '과일' },
      { ch: '苹果', py: 'píngguǒ', mean: '사과' },
      { ch: '香蕉', py: 'xiāngjiāo', mean: '바나나' },
      { ch: '西瓜', py: 'xīguā', mean: '수박' },
      { ch: '西红柿', py: 'xīhóngshì', mean: '토마토' },
      { ch: '葡萄', py: 'pútáo', mean: '포도' },
      { ch: '新鲜', py: 'xīnxiān', mean: '신선하다' },

      // --- 간식 및 음료 ---
      { ch: '面包', py: 'miànbāo', mean: '빵' },
      { ch: '蛋糕', py: 'dàngāo', mean: '케이크' },
      { ch: '巧克力', py: 'qiǎokèlì', mean: '초콜릿' },
      { ch: '饼干', py: 'bǐnggān', mean: '과자, 비스킷' },
      { ch: '小吃', py: 'xiǎochī', mean: '간식' },
      { ch: '饮料', py: 'yǐnliào', mean: '음료' },
      { ch: '牛奶', py: 'niúnǎi', mean: '우유' },
      { ch: '果汁', py: 'guǒzhī', mean: '과일 주스' },
      { ch: '矿泉水', py: 'kuàngquánshuǐ', mean: '생수' },
      { ch: '啤酒', py: 'píjiǔ', mean: '맥주' },

      // --- 식료품 및 조미료 ---
      { ch: '鸡蛋', py: 'jīdàn', mean: '계란' },
      { ch: '米', py: 'mǐ', mean: '쌀' },
      { ch: '面条', py: 'miàntiáo', mean: '국수' },
      { ch: '包子', py: 'bāozi', mean: '찐빵, 만두' },
      { ch: '鱼', py: 'yú', mean: '생선' },
      { ch: '糖', py: 'táng', mean: '설탕, 사탕' },
      { ch: '盐', py: 'yán', mean: '소금' },

      // --- 생활용품 및 기타 ---
      { ch: '牙膏', py: 'yágāo', mean: '치약' },
      { ch: '伞', py: 'sǎn', mean: '우산' },
      { ch: '刀', py: 'dāo', mean: '칼' },
      { ch: '瓶子', py: 'píngzi', mean: '병' },
      { ch: '质量', py: 'zhìliàng', mean: '품질' },
      { ch: '旧', py: 'jiù', mean: '낡다, 오래되다' },
    ],
  },

  {
    id: 7,
    title: '7) 외모 묘사 & 화장품',
    icon: '💄',
    words: [
      // --- 외모 형용사 ---
      { ch: '漂亮', py: 'piàoliang', mean: '예쁘다, 아름답다' },
      { ch: '帅', py: 'shuài', mean: '잘생기다, 멋지다' },
      { ch: '丑', py: 'chǒu', mean: '못생기다' },
      { ch: '高', py: 'gāo', mean: '(키가) 크다, 높다' },
      { ch: '矮', py: 'ǎi', mean: '(키가) 작다' },
      { ch: '长', py: 'cháng', mean: '길다' },
      { ch: '长', py: 'zhǎng', mean: '자라다, 생기다' },
      { ch: '白', py: 'bái', mean: '하얗다, 희다' },
      { ch: '娃娃脸', py: 'wáwaliǎn', mean: '동안' },
      { ch: '显得老', py: 'xiǎnde lǎo', mean: '나이 들어 보인다' },
      { ch: '外貌', py: 'wàimào', mean: '외모' },

      // --- 신체 및 착용물 ---
      { ch: '皮肤', py: 'pífū', mean: '피부' },
      { ch: '毛孔', py: 'máokǒng', mean: '모공' },
      { ch: '头发', py: 'tóufa', mean: '머리카락' },
      { ch: '眼镜', py: 'yǎnjìng', mean: '안경' },
      { ch: '太阳镜', py: 'tàiyángjìng', mean: '선글라스' },
      { ch: '耳环', py: 'ěrhuán', mean: '귀걸이' },
      { ch: '套装', py: 'tàozhuāng', mean: '정장, 슈트' },

      // --- 화장품 및 미용 ---
      { ch: '打扮', py: 'dǎban', mean: '꾸미다, 치장하다' },
      { ch: '化妆', py: 'huàzhuāng', mean: '화장하다' },
      { ch: '化妆品', py: 'huàzhuāngpǐn', mean: '화장품' },
      { ch: '美容', py: 'měiróng', mean: '미용' },
      { ch: '彩妆', py: 'cǎizhuāng', mean: '메이크업' },
      { ch: '美容手术', py: 'měiróng shǒushù', mean: '성형수술' },
      { ch: '理发', py: 'lǐfà', mean: '이발하다' },
      { ch: '脱', py: 'tuō', mean: '벗다' },

      // --- 화장품 상세 ---
      { ch: '面膜', py: 'miànmó', mean: '마스크팩' },
      { ch: '护肤水', py: 'hùfūshuǐ', mean: '스킨, 토너' },
      { ch: '乳液', py: 'rǔyè', mean: '로션' },
      { ch: '防晒霜', py: 'fángshàishuāng', mean: '선크림' },
      { ch: '粉底液', py: 'fěndǐyè', mean: '파운데이션' },
      { ch: '口红', py: 'kǒuhóng', mean: '립스틱' },
      { ch: '唇彩', py: 'chúncǎi', mean: '립글로스' },
      { ch: '护手霜', py: 'hùshǒushuāng', mean: '핸드크림' },
      { ch: '眉笔', py: 'méibǐ', mean: '아이브로우 펜슬' },

      // --- 부사 및 접속사 ---
      { ch: '非常', py: 'fēicháng', mean: '매우, 대단히' },
      { ch: '挺', py: 'tǐng', mean: '꽤, 매우' },
      { ch: '稍微', py: 'shāowēi', mean: '약간, 조금' },
      { ch: '一点儿', py: 'yìdiǎnr', mean: '조금, 약간' },
      { ch: '当然', py: 'dāngrán', mean: '당연히' },
      { ch: '流行', py: 'liúxíng', mean: '유행하다' },
      { ch: '正确', py: 'zhèngquè', mean: '정확하다' },
      { ch: '全部', py: 'quánbù', mean: '전부, 전체' },
      { ch: '差', py: 'chà', mean: '부족하다, 나쁘다' },
      { ch: '相反', py: 'xiāngfǎn', mean: '반대로' },
      { ch: '无论', py: 'wúlùn', mean: '~을 막론하고' },
    ],
  },

  {
    id: 8,
    title: '8) 식사 및 주문하기',
    icon: '🍜',
    words: [
      // --- 동작 (먹다/마시다) ---
      { ch: '吃', py: 'chī', mean: '먹다' },
      { ch: '喝', py: 'hē', mean: '마시다' },
      { ch: '尝', py: 'cháng', mean: '맛보다' },
      { ch: '包', py: 'bāo', mean: '포장하다, 싸다' },
      { ch: '剩', py: 'shèng', mean: '남기다, 남다' },
      { ch: '举', py: 'jǔ', mean: '들다, 들어올리다' },
      { ch: '干杯', py: 'gānbēi', mean: '건배하다' },
      { ch: '使用', py: 'shǐyòng', mean: '사용하다' },
      { ch: '用', py: 'yòng', mean: '쓰다, 사용하다' },

      // --- 음식 및 음료 ---
      { ch: '菜', py: 'cài', mean: '요리, 반찬, 채소' },
      { ch: '米饭', py: 'mǐfàn', mean: '쌀밥' },
      { ch: '面条', py: 'miàntiáo', mean: '국수' },
      { ch: '饺子', py: 'jiǎozi', mean: '만두, 교자' },
      { ch: '包子', py: 'bāozi', mean: '찐빵, 만두' },
      { ch: '烤鸭', py: 'kǎoyā', mean: '오리구이' },
      { ch: '羊肉', py: 'yángròu', mean: '양고기' },
      { ch: '鱼', py: 'yú', mean: '생선' },
      { ch: '汤', py: 'tāng', mean: '국물, 탕' },
      { ch: '鸡蛋', py: 'jīdàn', mean: '계란' },
      { ch: '茶', py: 'chá', mean: '차' },
      { ch: '水', py: 'shuǐ', mean: '물' },
      { ch: '咖啡', py: 'kāfēi', mean: '커피' },
      { ch: '糖', py: 'táng', mean: '설탕, 사탕' },
      { ch: '盐', py: 'yán', mean: '소금' },

      // --- 식당 및 도구 ---
      { ch: '餐厅', py: 'cāntīng', mean: '식당' },
      { ch: '服务员', py: 'fúwùyuán', mean: '종업원' },
      { ch: '菜单', py: 'càidān', mean: '메뉴판' },
      { ch: '筷子', py: 'kuàizi', mean: '젓가락' },
      { ch: '勺子', py: 'sháozi', mean: '숟가락' },
      { ch: '杯子', py: 'bēizi', mean: '잔, 컵' },
      { ch: '位', py: 'wèi', mean: '(양사) 분 (사람 세는 단위)' },

      // --- 맛과 상태 ---
      { ch: '味道', py: 'wèidao', mean: '맛, 냄새' },
      { ch: '好吃', py: 'hàochī', mean: '맛있다' },
      { ch: '香', py: 'xiāng', mean: '향기롭다, 맛있다' },
      { ch: '甜', py: 'tián', mean: '달다' },
      { ch: '辣', py: 'là', mean: '맵다' },
      { ch: '酸', py: 'suān', mean: '시다' },
      { ch: '苦', py: 'kǔ', mean: '쓰다' },
      { ch: '咸', py: 'xián', mean: '짜다' },
      { ch: '饿', py: 'è', mean: '배고프다' },
      { ch: '饱', py: 'bǎo', mean: '배부르다' },
      { ch: '渴', py: 'kě', mean: '목마르다' },

      // --- 사람 및 기타 ---
      { ch: '客人', py: 'kèrén', mean: '손님' },
      { ch: '顾客', py: 'gùkè', mean: '고객' },
      { ch: '免费', py: 'miǎnfèi', mean: '무료' },
      { ch: '所有', py: 'suǒyǒu', mean: '모든, 전부의' },
    ],
  },

  {
    id: 9,
    title: '9) 숫자 및 가격',
    icon: '💰',
    words: [
      // --- 숫자 및 단위 ---
      { ch: '零', py: 'líng', mean: '0, 영' },
      { ch: '百', py: 'bǎi', mean: '100, 백' },
      { ch: '千', py: 'qiān', mean: '1000, 천' },
      { ch: '万', py: 'wàn', mean: '10000, 만' },
      { ch: '数字', py: 'shùzì', mean: '숫자' },
      { ch: '数量', py: 'shùliàng', mean: '수량' },
      { ch: '块', py: 'kuài', mean: '위안 (화폐 단위)' },
      { ch: '角', py: 'jiǎo', mean: '지아오 (0.1위안)' },
      { ch: '些', py: 'xiē', mean: '약간, 조금 (양사)' },
      { ch: '种', py: 'zhǒng', mean: '종류 (양사)' },

      // --- 가격 및 거래 ---
      { ch: '钱', py: 'qián', mean: '돈' },
      { ch: '价格', py: 'jiàgé', mean: '가격' },
      { ch: '贵', py: 'guì', mean: '비싸다' },
      { ch: '便宜', py: 'piányi', mean: '싸다' },
      { ch: '打折', py: 'dǎzhé', mean: '할인하다, 세일하다' },
      { ch: '付款', py: 'fùkuǎn', mean: '지불하다' },
      { ch: '找', py: 'zhǎo', mean: '거슬러 주다, 찾다' },
      { ch: '花', py: 'huā', mean: '(돈을) 쓰다, 꽃' },

      // --- 동사 및 형용사 ---
      { ch: '觉得', py: 'juéde', mean: '~라고 생각하다(느끼다)' },
      { ch: '比较', py: 'bǐjiào', mean: '비교하다, 비교적' },
      { ch: '要', py: 'yào', mean: '원하다, ~해야 한다' },
      { ch: '可以', py: 'kěyǐ', mean: '가능하다, ~해도 된다' },
      { ch: '多', py: 'duō', mean: '많다' },
      { ch: '长', py: 'cháng', mean: '길다' },
      { ch: '短', py: 'duǎn', mean: '짧다' },
      { ch: '正好', py: 'zhènghǎo', mean: '딱 맞다, 마침' },

      // --- 부사 및 조사 ---
      { ch: '太…了', py: 'tài…le', mean: '너무 ~하다' },
      { ch: '已经…了', py: 'yǐjīng…le', mean: '이미, 벌써' },
      { ch: '先', py: 'xiān', mean: '먼저, 우선' },
      { ch: '可能', py: 'kěnéng', mean: '아마도, 가능하다' },
      { ch: '刚才', py: 'gāngcái', mean: '방금, 막' },
      { ch: '只', py: 'zhǐ', mean: '오직, 단지' },
      { ch: '经常', py: 'jīngcháng', mean: '자주' },
      { ch: '又', py: 'yòu', mean: '또, 다시 (과거/반복)' },
      { ch: '再', py: 'zài', mean: '다시 (미래)' },
      { ch: '还', py: 'hái', mean: '아직, 더, 또' },
      { ch: '别', py: 'bié', mean: '~하지 마라' },
      { ch: '总是', py: 'zǒngshì', mean: '언제나, 늘' },
      { ch: '得', py: 'de', mean: '(정도보어 조사)' },
      { ch: '地', py: 'de', mean: '(부사어 조사)' },
    ],
  },

  {
    id: 10,
    title: '10) 약속잡기 및 데이트',
    icon: '💑',
    words: [
      // --- 감정 및 태도 ---
      { ch: '爱', py: 'ài', mean: '사랑하다, 좋아하다' },
      { ch: '喜欢', py: 'xǐhuan', mean: '좋아하다' },
      { ch: '爱情', py: 'àiqíng', mean: '사랑, 애정' },
      { ch: '感情', py: 'gǎnqíng', mean: '감정' },
      { ch: '友谊', py: 'yǒuyì', mean: '우정' },
      { ch: '怀疑', py: 'huáiyí', mean: '의심하다' },
      { ch: '误会', py: 'wùhuì', mean: '오해하다, 오해' },
      { ch: '难过', py: 'nánguò', mean: '괴롭다, 슬프다' },
      { ch: '热闹', py: 'rènao', mean: '떠들썩하다, 번화하다' },
      { ch: '真', py: 'zhēn', mean: '정말, 진짜로' },
      { ch: '深', py: 'shēn', mean: '(감정이) 깊다' },

      // --- 만남과 소통 ---
      { ch: '约会', py: 'yuēhuì', mean: '데이트하다, 약속' },
      { ch: '见面', py: 'jiànmiàn', mean: '만나다' },
      { ch: '等', py: 'děng', mean: '기다리다' },
      { ch: '迟到', py: 'chídào', mean: '지각하다' },
      { ch: '聊天', py: 'liáotiān', mean: '이야기하다, 수다 떨다' },
      { ch: '说', py: 'shuō', mean: '말하다' },
      { ch: '说话', py: 'shuōhuà', mean: '말하다, 이야기하다' },
      { ch: '开玩笑', py: 'kāi wánxiào', mean: '농담하다' },
      { ch: '交', py: 'jiāo', mean: '사귀다' },
      { ch: '离开', py: 'líkāi', mean: '떠나다, 헤어지다' },
      { ch: '抱', py: 'bào', mean: '안다, 포옹하다' },
      { ch: '请', py: 'qǐng', mean: '초대하다' },
      { ch: '逛', py: 'guàng', mean: '거닐다, 구경하다' },

      // --- 연락 수단 ---
      { ch: '打电话', py: 'dǎ diànhuà', mean: '전화하다' },
      { ch: '发', py: 'fā', mean: '보내다' },
      { ch: '短信', py: 'duǎnxìn', mean: '문자 메시지' },
      { ch: '号码', py: 'hàomă', mean: '번호' },
      { ch: '占线', py: 'zhànxiàn', mean: '통화 중이다' },

      // --- 인물 및 호칭 ---
      { ch: '男', py: 'nán', mean: '남자, 남성' },
      { ch: '女', py: 'nǚ', mean: '여자, 여성' },
      { ch: '俩', py: 'liǎ', mean: '두 사람 (둘)' },
      { ch: '两人', py: 'liǎng ge rén', mean: '두 사람' },

      // --- 이벤트 및 선물 ---
      { ch: '生日', py: 'shēngrì', mean: '생일' },
      { ch: '礼物', py: 'lǐwù', mean: '선물' },
      { ch: '电影', py: 'diànyǐng', mean: '영화' },
      { ch: '结婚', py: 'jiéhūn', mean: '결혼하다' },
      { ch: '离婚', py: 'líhūn', mean: '이혼하다' },
      { ch: '婚礼', py: 'hūnlǐ', mean: '결혼식' },

      // --- 조사 및 기타 ---
      { ch: '给', py: 'gěi', mean: '주다, ~에게' },
      { ch: '跟', py: 'gēn', mean: '~와, ~에게' },
      { ch: '和', py: 'hé', mean: '~와 (함께)' },
      { ch: '一般', py: 'yìbān', mean: '보통이다' },
    ],
  },

  {
    id: 11,
    title: '11) 길 찾기 & 방향',
    icon: '🗺️',
    words: [
      // --- 방향 및 위치 ---
      { ch: '前面', py: 'qiánmiàn', mean: '앞, 앞쪽' },
      { ch: '后面', py: 'hòumiàn', mean: '뒤, 뒤쪽' },
      { ch: '左边', py: 'zuǒbian', mean: '왼쪽' },
      { ch: '右边', py: 'yòubian', mean: '오른쪽' },
      { ch: '对面', py: 'duìmiàn', mean: '맞은편, 건너편' },
      { ch: '旁边', py: 'pángbiān', mean: '옆, 근처' },
      { ch: '附近', py: 'fùjìn', mean: '부근, 근처' },
      { ch: '周围', py: 'zhōuwéi', mean: '주변, 주위' },
      { ch: '方向', py: 'fāngxiàng', mean: '방향' },
      { ch: '哪儿', py: 'nǎr', mean: '어디' },
      { ch: '东', py: 'dōng', mean: '동쪽' },
      { ch: '西', py: 'xī', mean: '서쪽' },
      { ch: '南', py: 'nán', mean: '남쪽' },
      { ch: '北方', py: 'běifāng', mean: '북쪽' },

      // --- 이동 동사 ---
      { ch: '去', py: 'qù', mean: '가다' },
      { ch: '来', py: 'lái', mean: '오다' },
      { ch: '走', py: 'zǒu', mean: '걷다, 가다' },
      { ch: '回', py: 'huí', mean: '돌아가다' },
      { ch: '进', py: 'jìn', mean: '들어가다' },
      { ch: '出', py: 'chū', mean: '나가다, 나오다' },
      { ch: '过', py: 'guò', mean: '건너다, 지나다' },
      { ch: '过去', py: 'guòqù', mean: '지나가다' },
      { ch: '经过', py: 'jīngguò', mean: '경유하다, 지나가다' },
      { ch: '转', py: 'zhuǎn', mean: '돌다, 꺾다 (방향)' },
      { ch: '停', py: 'tíng', mean: '멈추다, 서다' },
      { ch: '赶', py: 'gǎn', mean: '서둘러 가다, 따라잡다' },

      // --- 거리 및 도로 ---
      { ch: '路', py: 'lù', mean: '길, 도로' },
      { ch: '街道', py: 'jiēdào', mean: '거리, 가로' },
      { ch: '距离', py: 'jùlí', mean: '거리, 간격' },
      { ch: '公里', py: 'gōnglǐ', mean: '킬로미터 (km)' },
      { ch: '近', py: 'jìn', mean: '가깝다' },
      { ch: '远', py: 'yuǎn', mean: '멀다' },
      { ch: '加油站', py: 'jiāyóuzhàn', mean: '주유소' },

      // --- 전치사(개사) ---
      { ch: '从', py: 'cóng', mean: '~에서, ~부터 (기점)' },
      { ch: '离', py: 'lí', mean: '~에서 (거리 기준)' },
      { ch: '往', py: 'wǎng', mean: '~쪽으로' },
      { ch: '向', py: 'xiàng', mean: '~을 향하여' },

      // --- 사람 호칭 및 기타 ---
      { ch: '先生', py: 'xiānsheng', mean: '선생님, 미스터' },
      { ch: '小姐', py: 'xiǎojiě', mean: '아가씨, 미스' },
      { ch: '过', py: 'guo', mean: '~한 적이 있다 (경험)' }, // 동사 뒤에 쓰이는 조사
    ],
  },

  {
    id: 12,
    title: '12) 집안일 하기',
    icon: '🧹',
    words: [
      // --- 청소 및 동작 ---
      { ch: '做', py: 'zuò', mean: '하다, 만들다' },
      { ch: '打扫', py: 'dǎsǎo', mean: '청소하다' },
      { ch: '收拾', py: 'shōushi', mean: '정리하다, 수습하다' },
      { ch: '整理', py: 'zhěnglǐ', mean: '정리하다' },
      { ch: '关', py: 'guān', mean: '끄다, 닫다' },
      { ch: '听', py: 'tīng', mean: '듣다' },
      { ch: '敲', py: 'qiāo', mean: '두드리다' },
      { ch: '响', py: 'xiǎng', mean: '소리가 나다, 울리다' },
      { ch: '养成', py: 'yǎngchéng', mean: '기르다, 습관이 되다' },
      { ch: '增加', py: 'zēngjiā', mean: '증가하다' },
      { ch: '让', py: 'ràng', mean: '~하게 시키다' },

      // --- 집안 장소 ---
      { ch: '房间', py: 'fángjiān', mean: '방' },
      { ch: '客厅', py: 'kètīng', mean: '거실' },
      { ch: '厨房', py: 'chúfáng', mean: '주방, 부엌' },
      { ch: '洗手间', py: 'xǐshǒujiān', mean: '화장실' },
      { ch: '卫生间', py: 'wèishēngjiān', mean: '화장실' },
      { ch: '厕所', py: 'cèsuǒ', mean: '변소, 화장실' },
      { ch: '里', py: 'lǐ', mean: '안, 속' },

      // --- 사물 및 가구 ---
      { ch: '窗户', py: 'chuānghu', mean: '창문' },
      { ch: '灯', py: 'dēng', mean: '등, 램프' },
      { ch: '垃圾桶', py: 'lājītǒng', mean: '쓰레기통' },
      { ch: '冰箱', py: 'bīngxiāng', mean: '냉장고' },
      { ch: '盘子', py: 'pánzi', mean: '쟁반, 접시' },
      { ch: '碗', py: 'wǎn', mean: '그릇, 공기' },
      { ch: '日记', py: 'rìjì', mean: '일기' },

      // --- 상태 및 형용사 ---
      { ch: '干净', py: 'gānjìng', mean: '깨끗하다' },
      { ch: '脏', py: 'zāng', mean: '더럽다' },

      // --- 문법 및 접속사 ---
      { ch: '正在', py: 'zhèngzài', mean: '지금 ~하고 있다 (진행)' },
      { ch: '以前', py: 'yǐqián', mean: '이전, 예전' },
      { ch: '也', py: 'yě', mean: '~도, 역시' },
      { ch: '一起', py: 'yìqǐ', mean: '같이, 함께' },
      { ch: '不过', py: 'búguò', mean: '그러나, 그런데' },
      { ch: '因此', py: 'yīncǐ', mean: '그래서, 이 때문에' },
      { ch: '要是', py: 'yàoshi', mean: '만약 ~라면' },
      { ch: '必须', py: 'bìxū', mean: '반드시 ~해야 한다' },
      { ch: '除了', py: 'chúle', mean: '~을 제외하고' },
      { ch: '由', py: 'yóu', mean: '~에 의해, ~로' },
      { ch: '把', py: 'bǎ', mean: '~을 (처치문)' },
      { ch: '被', py: 'bèi', mean: '~에게 당하다 (피동문)' },
      { ch: '张', py: 'zhāng', mean: '(양사) 장, 개' },
    ],
  },

  {
    id: 13,
    title: '13) 공부하기',
    icon: '📚',
    words: [
      // --- 학습 동작 ---
      { ch: '学习', py: 'xuéxí', mean: '공부하다' },
      { ch: '练习', py: 'liànxí', mean: '연습하다' },
      { ch: '预习', py: 'yùxí', mean: '예습하다' },
      { ch: '问', py: 'wèn', mean: '묻다, 질문하다' },
      { ch: '借', py: 'jiè', mean: '빌리다' },
      { ch: '还', py: 'huán', mean: '반납하다, 돌려주다' },
      { ch: '猜', py: 'cāi', mean: '맞히다, 추측하다' },
      { ch: '试', py: 'shì', mean: '시험하다, 시도하다' },
      { ch: '申请', py: 'shēnqǐng', mean: '신청하다' },
      { ch: '留学', py: 'liúxué', mean: '유학하다' },
      { ch: '证明', py: 'zhèngmíng', mean: '증명하다' },
      { ch: '毕业', py: 'bìyè', mean: '졸업하다' },
      { ch: '翻译', py: 'fānyì', mean: '번역하다, 통역하다' },
      { ch: '理解', py: 'lǐjiě', mean: '이해하다' },
      { ch: '解释', py: 'jiěshì', mean: '설명하다, 해석하다' },
      { ch: '提高', py: 'tígāo', mean: '향상시키다' },
      { ch: '积累', py: 'jīlěi', mean: '쌓이다, 누적되다' },
      { ch: '估计', py: 'gūjì', mean: '예측하다, 추측하다' },

      // --- 시험 및 성과 ---
      { ch: '问题', py: 'wèntí', mean: '문제' },
      { ch: '答案', py: "dá'àn", mean: '정답, 답안' },
      { ch: '填空', py: 'tiánkòng', mean: '빈칸을 채우다' },
      { ch: '成绩', py: 'chéngjì', mean: '성적' },
      { ch: '水平', py: 'shuǐpíng', mean: '수준' },
      { ch: '通过', py: 'tōngguò', mean: '통과하다' },
      { ch: '合格', py: 'hégé', mean: '합격하다' },
      { ch: '奖金', py: 'jiǎngjīn', mean: '상금, 장학금' },
      { ch: '优秀', py: 'yōuxiù', mean: '우수하다' },

      // --- 언어 및 지식 ---
      { ch: '中文', py: 'Zhōngwén', mean: '중국어' },
      { ch: '普通话', py: 'pǔtōnghuà', mean: '중국 표준어' },
      { ch: '词语', py: 'cíyǔ', mean: '어휘, 단어' },
      { ch: '语法', py: 'yǔfǎ', mean: '문법, 어법' },
      { ch: '基础', py: 'jīchǔ', mean: '기초' },
      { ch: '知识', py: 'zhīshi', mean: '지식' },
      { ch: '流利', py: 'liúlì', mean: '유창하다' },
      { ch: '聪明', py: 'cōngming', mean: '똑똑하다' },

      // --- 학교 관련 명사 ---
      { ch: '作业', py: 'zuòyè', mean: '숙제, 과제' },
      { ch: '图书馆', py: 'túshūguǎn', mean: '도서관' },
      { ch: '笔记本', py: 'bǐjìběn', mean: '노트, 수첩, 노트북' },
      { ch: '硕士', py: 'shuòshì', mean: '석사' },
      { ch: '博士', py: 'bóshì', mean: '박사' },
    ],
  },

  {
    id: 14,
    title: '14) 이사 및 꾸미기',
    icon: '📦',
    words: [
      // --- 주거 및 건물 ---
      { ch: '家', py: 'jiā', mean: '집, 가정' },
      { ch: '住', py: 'zhù', mean: '살다, 거주하다' },
      { ch: '楼', py: 'lóu', mean: '층, 건물' },
      { ch: '层', py: 'céng', mean: '(양사) 층' },
      { ch: '电梯', py: 'diàntī', mean: '엘리베이터' },
      { ch: '门', py: 'mén', mean: '문, 입구' },
      { ch: '邻居', py: 'línjū', mean: '이웃' },
      { ch: '房东', py: 'fángdōng', mean: '집주인' },
      { ch: '租', py: 'zū', mean: '임대하다, 세내다' },
      { ch: '钥匙', py: 'yàoshi', mean: '열쇠' },
      { ch: '密码', py: 'mìmǎ', mean: '비밀번호' },

      // --- 가구 및 물건 ---
      { ch: '家具', py: 'jiāju', mean: '가구' },
      { ch: '桌子', py: 'zhuōzi', mean: '책상, 탁자' },
      { ch: '沙发', py: 'shāfā', mean: '소파' },
      { ch: '镜子', py: 'jìngzi', mean: '거울' },
      { ch: '空调', py: 'kōngtiáo', mean: '에어컨' },
      { ch: '盒子', py: 'hézi', mean: '상자, 박스' },
      { ch: '台', py: 'tái', mean: '(양사) 대 (기계 세는 단위)' },

      // --- 이사 및 동작 ---
      { ch: '搬', py: 'bān', mean: '옮기다, 이사하다' },
      { ch: '抬', py: 'tái', mean: '들어 올리다, (같이) 들다' },
      { ch: '推', py: 'tuī', mean: '밀다' },
      { ch: '扔', py: 'rēng', mean: '던지다, 버리다' },
      { ch: '挂', py: 'guà', mean: '걸다' },
      { ch: '倒', py: 'dào', mean: '따르다, (쓰레기를) 버리다' },
      { ch: '修理', py: 'xiūlǐ', mean: '수리하다' },
      { ch: '帮助', py: 'bāngzhù', mean: '돕다, 도움' },
      { ch: '帮忙', py: 'bāngmáng', mean: '도와주다' },

      // --- 상태 및 형용사 ---
      { ch: '重', py: 'zhòng', mean: '무겁다' },
      { ch: '空', py: 'kōng', mean: '비다, 공허하다' },
      { ch: '满', py: 'mǎn', mean: '가득 차다' },
      { ch: '乱', py: 'luàn', mean: '어지럽다, 무질서하다' },
      { ch: '破', py: 'pò', mean: '망가지다, 찢어지다' },
      { ch: '坏', py: 'huài', mean: '고장 나다, 나쁘다' },
      { ch: '熟悉', py: 'shúxī', mean: '익숙하다' },

      // --- 기타 표현 ---
      { ch: '着', py: 'zhe', mean: '~하고 있다 (상태 지속)' },
      { ch: '互相', py: 'hùxiāng', mean: '서로' },
      { ch: '方法', py: 'fāngfǎ', mean: '방법' },
      { ch: '功夫', py: 'gōngfu', mean: '시간, 틈, 쿵푸' },
      { ch: '左右', py: 'zuǒyòu', mean: '정도, 쯤 (수량 뒤)' },
      { ch: '一会儿', py: 'yíhuìr', mean: '잠시, 곧' },
    ],
  },

  {
    id: 15,
    title: '15) 감정 표현하기',
    icon: '😄',
    words: [
      // --- 긍정적 감정 ---
      { ch: '高兴', py: 'gāoxìng', mean: '기쁘다' },
      { ch: '开心', py: 'kāixīn', mean: '즐겁다, 유쾌하다' },
      { ch: '快乐', py: 'kuàilè', mean: '행복하다, 즐겁다' },
      { ch: '愉快', py: 'yúkuài', mean: '유쾌하다' },
      { ch: '满意', py: 'mǎnyì', mean: '만족하다' },
      { ch: '兴奋', py: 'xīngfèn', mean: '흥분하다' },
      { ch: '激动', py: 'jīdòng', mean: '감격하다, 흥분하다' },
      { ch: '感动', py: 'gǎndòng', mean: '감동하다' },
      { ch: '得意', py: 'déyì', mean: '자랑스러워하다, 득의양양하다' },

      // --- 부정적 감정 ---
      { ch: '难过', py: 'nánguò', mean: '괴롭다, 슬프다' },
      { ch: '哭', py: 'kū', mean: '울다' },
      { ch: '生气', py: 'shēngqì', mean: '화내다' },
      { ch: '担心', py: 'dānxīn', mean: '걱정하다' },
      { ch: '害怕', py: 'hàipà', mean: '무서워하다, 두려워하다' },
      { ch: '紧张', py: 'jǐnzhāng', mean: '긴장하다' },
      { ch: '失望', py: 'shīwàng', mean: '실망하다' },
      { ch: '讨厌', py: 'tǎoyàn', mean: '싫어하다' },
      { ch: '烦恼', py: 'fánnǎo', mean: '고민하다, 번뇌하다' },
      { ch: '可惜', py: 'kěxī', mean: '아쉽다, 아깝다' },
      { ch: '可怜', py: 'kělián', mean: '불쌍하다' },
      { ch: '后悔', py: 'hòuhuǐ', mean: '후회하다' }, // 원문에 없지만 자주 쓰임 (참고)
      { ch: '吃惊', py: 'chījīng', mean: '놀라다' },

      // --- 평가 및 태도 ---
      { ch: '精彩', py: 'jīngcǎi', mean: '훌륭하다, 멋지다' },
      { ch: '有趣', py: 'yǒuqù', mean: '재미있다' },
      { ch: '无聊', py: 'wúliáo', mean: '지루하다, 심심하다' },
      { ch: '容易', py: 'róngyì', mean: '쉽다' },
      { ch: '难', py: 'nán', mean: '어렵다' },
      { ch: '辛苦', py: 'xīnku', mean: '수고하다, 고생스럽다' },
      { ch: '麻烦', py: 'máfan', mean: '번거롭다, 폐를 끼치다' },
      { ch: '困', py: 'kùn', mean: '졸리다' },
      { ch: '羡慕', py: 'xiànmù', mean: '부러워하다' },
      { ch: '同情', py: 'tóngqíng', mean: '동정하다' },
      { ch: '抱歉', py: 'bàoqiàn', mean: '미안하다' },
      { ch: '错误', py: 'cuòwù', mean: '잘못, 실수' },

      // --- 상호작용 (동사) ---
      { ch: '鼓励', py: 'gǔlì', mean: '격려하다' },
      { ch: '表扬', py: 'biǎoyáng', mean: '칭찬하다' },
      { ch: '批评', py: 'pīpíng', mean: '비판하다, 꾸짖다' },
      { ch: '反对', py: 'fǎnduì', mean: '반대하다' },
      { ch: '骗', py: 'piàn', mean: '속이다' },
      { ch: '允许', py: 'yǔnxǔ', mean: '허락하다' },
      { ch: '符合', py: 'fúhé', mean: '부합하다, 일치하다' },
      { ch: '失败', py: 'shībài', mean: '실패하다' },
    ],
  },

  {
    id: 16,
    title: '16) 성격 표현하기',
    icon: '😎',
    words: [
      // --- 성격 및 태도 (긍정/중립) ---
      { ch: '性格', py: 'xìnggé', mean: '성격' },
      { ch: '脾气', py: 'píqi', mean: '성질, 성격' },
      { ch: '可爱', py: "kě'ài", mean: '귀엽다' },
      { ch: '热情', py: 'rèqíng', mean: '친절하다, 열정적이다' },
      { ch: '幽默', py: 'yōumò', mean: '유머러스하다' },
      { ch: '活泼', py: 'huópō', mean: '활발하다' },
      { ch: '安静', py: 'ānjìng', mean: '조용하다' },
      { ch: '仔细', py: 'zǐxì', mean: '꼼꼼하다, 자세하다' },
      { ch: '细心', py: 'xìxīn', mean: '세심하다, 꼼꼼하다' },
      { ch: '冷静', py: 'lěngjìng', mean: '냉정하다, 침착하다' },
      { ch: '积极', py: 'jījí', mean: '적극적이다' },
      { ch: '勇敢', py: 'yǒnggǎn', mean: '용감하다' },
      { ch: '诚实', py: 'chéngshí', mean: '성실하다, 정직하다' },
      { ch: '耐心', py: 'nàixīn', mean: '인내심' },
      { ch: '礼貌', py: 'lǐmào', mean: '예의 바르다' },
      { ch: '浪漫', py: 'làngmàn', mean: '낭만적이다' },
      { ch: '友好', py: 'yǒuhǎo', mean: '우호적이다' },

      // --- 성격 및 태도 (부정/기타) ---
      { ch: '害羞', py: 'hàixiū', mean: '수줍어하다, 부끄러워하다' },
      { ch: '着急', py: 'zháojí', mean: '조급해하다' },
      { ch: '粗心', py: 'cūxīn', mean: '부주의하다, 덜렁대다' },
      { ch: '骄傲', py: "jiāo'ào", mean: '거만하다, 자랑스럽다' },
      { ch: '懒', py: 'lǎn', mean: '게으르다' },
      { ch: '马虎', py: 'mǎhu', mean: '대강하다, 세심하지 못하다' },
      { ch: '严格', py: 'yángé', mean: '엄격하다' },
      { ch: '厉害', py: 'lìhai', mean: '대단하다, 독하다' },
      { ch: '笨', py: 'bèn', mean: '멍청하다, 어리석다' },
      { ch: '小心', py: 'xiǎoxīn', mean: '조심하다' },
      { ch: '愿意', py: 'yuànyì', mean: '원하다, 바라다' },
      { ch: '后悔', py: 'hòuhuǐ', mean: '후회하다' },
      { ch: '懂', py: 'dǒng', mean: '알다, 이해하다' },

      // --- 부사 및 접속사 ---
      { ch: '十分', py: 'shífēn', mean: '매우, 대단히' },
      { ch: '完全', py: 'wánquán', mean: '완전히' },
      { ch: '肯定', py: 'kěndìng', mean: '틀림없이, 긍정하다' },
      { ch: '不管', py: 'bùguǎn', mean: '~에 관계없이' },
      { ch: '不仅', py: 'bùjǐn', mean: '~뿐만 아니라' },
      { ch: '而', py: 'ér', mean: '그러나, 그리고 (접속사)' },
      { ch: '并且', py: 'bìngqiě', mean: '게다가, 또한' },
      { ch: '根据', py: 'gēnjù', mean: '~에 근거하여' },
      { ch: '之', py: 'zhī', mean: '~의 (관형어 조사)' },
      { ch: '哪', py: 'nǎ', mean: '어느, 어떤' },
      { ch: '各', py: 'gè', mean: '각, 여러' },
    ],
  },

  {
    id: 17,
    title: '17) 의견 교류하기',
    icon: '🗣️',
    words: [
      // --- 소통 및 대화 ---
      { ch: '交流', py: 'jiāoliú', mean: '교류하다, 소통하다' },
      { ch: '谈', py: 'tán', mean: '이야기하다' },
      { ch: '说话', py: 'shuōhuà', mean: '말하다' }, // 10과와 중복되지만 중요해서 포함
      { ch: '对话', py: 'duìhuà', mean: '대화하다' },
      { ch: '讨论', py: 'tǎolùn', mean: '토론하다' },
      { ch: '联系', py: 'liánxì', mean: '연락하다' },
      { ch: '打招呼', py: 'dǎ zhāohu', mean: '인사하다' },
      { ch: '遇到', py: 'yùdào', mean: '우연히 만나다, 마주치다' },
      { ch: '聚会', py: 'jùhuì', mean: '모임, 회식' },
      { ch: '电子邮件', py: 'diànzǐ yóujiàn', mean: '이메일' },

      // --- 의견 및 태도 ---
      { ch: '看法', py: 'kànfǎ', mean: '견해, 생각' },
      { ch: '态度', py: 'tàidu', mean: '태도' },
      { ch: '同意', py: 'tóngyì', mean: '동의하다, 찬성하다' },
      { ch: '拒绝', py: 'jùjué', mean: '거절하다' },
      { ch: '接受', py: 'jiēshòu', mean: '받아들이다, 수락하다' },
      { ch: '反对', py: 'fǎnduì', mean: '반대하다' }, // 15과 중복, 복습용
      { ch: '尊重', py: 'zūnzhòng', mean: '존중하다' },
      { ch: '重视', py: 'zhòngshì', mean: '중시하다' },
      { ch: '关心', py: 'guānxīn', mean: '관심을 갖다' },
      { ch: '欢迎', py: 'huānyíng', mean: '환영하다' },
      { ch: '打扰', py: 'dǎrǎo', mean: '방해하다, 폐를 끼치다' },
      { ch: '自信', py: 'zìxìn', mean: '자신감, 자신만만하다' },

      // --- 생각 및 인지 ---
      { ch: '认识', py: 'rènshi', mean: '알다, 인식하다' },
      { ch: '以为', py: 'yǐwéi', mean: '(사실과 달리) ~인 줄 알았다' },
      { ch: '回忆', py: 'huíyì', mean: '추억하다, 회상' },
      { ch: '详细', py: 'xiángxì', mean: '상세하다, 자세하다' },

      // --- 상태 및 관계 ---
      { ch: '关系', py: 'guānxi', mean: '관계' },
      { ch: '久', py: 'jiǔ', mean: '오래다 (시간)' },
      { ch: '相同', py: 'xiāngtóng', mean: '서로 같다' },
      { ch: '共同', py: 'gòngtóng', mean: '공동의' },
      { ch: '真正', py: 'zhēnzhèng', mean: '진정한' },
      { ch: '困难', py: 'kùnnan', mean: '어려움, 곤란하다' },
      { ch: '条件', py: 'tiáojiàn', mean: '조건' },
      { ch: '规定', py: 'guīdìng', mean: '규정, 정하다' },
      { ch: '过程', py: 'guòchéng', mean: '과정' },
      { ch: '国际', py: 'guójì', mean: '국제' },
      { ch: '语言', py: 'yǔyán', mean: '언어' },

      // --- 부사 및 접속사 ---
      { ch: '怎么', py: 'zěnme', mean: '어떻게, 왜' },
      { ch: '却', py: 'què', mean: '오히려, 도리어' },
      { ch: '一直', py: 'yìzhí', mean: '줄곧, 계속' },
      { ch: '往往', py: 'wǎngwǎng', mean: '자주, 종종' },
      { ch: '任何', py: 'rènhé', mean: '어떠한' },
    ],
  },

  {
    id: 18,
    title: '18) 소개하기',
    icon: '🤝',
    words: [
      // --- 신상 정보 ---
      { ch: '介绍', py: 'jièshào', mean: '소개하다' },
      { ch: '叫', py: 'jiào', mean: '~라고 부르다' },
      { ch: '名字', py: 'míngzi', mean: '이름' },
      { ch: '姓', py: 'xìng', mean: '성이 ~이다' },
      { ch: '年龄', py: 'niánlíng', mean: '나이, 연령' },
      { ch: '岁', py: 'suì', mean: '살, 세 (나이)' },
      { ch: '性别', py: 'xìngbié', mean: '성별' },
      { ch: '地址', py: 'dìzhǐ', mean: '주소' },
      { ch: '来自', py: 'láizì', mean: '~에서 오다' },
      { ch: '谁', py: 'shéi', mean: '누구' },

      // --- 인물 특징 및 상태 ---
      { ch: '年轻', py: 'niánqīng', mean: '젊다' },
      { ch: '大', py: 'dà', mean: '크다, (나이가) 많다' },
      { ch: '小', py: 'xiǎo', mean: '작다, 어리다' },
      { ch: '像', py: 'xiàng', mean: '닮다, 비슷하다' },
      { ch: '好像', py: 'hǎoxiàng', mean: '마치 ~인 것 같다' },
      { ch: '特点', py: 'tèdiǎn', mean: '특징' },
      { ch: '优点', py: 'yōudiǎn', mean: '장점' },
      { ch: '好处', py: 'hǎochu', mean: '이로운 점, 장점' },
      { ch: '幸福', py: 'xìngfú', mean: '행복하다' },
      { ch: '实际', py: 'shíjì', mean: '실제적이다, 구체적이다' },

      // --- 행동 및 관계 ---
      { ch: '照顾', py: 'zhàogù', mean: '돌보다, 보살피다' },
      { ch: '孩子', py: 'háizi', mean: '아이' },
      { ch: '相信', py: 'xiāngxìn', mean: '믿다, 신뢰하다' },
      { ch: '生意', py: 'shēngyi', mean: '장사, 사업' },
      { ch: '继续', py: 'jìxù', mean: '계속하다' },
      { ch: '重新', py: 'chóngxīn', mean: '다시, 재차' },
      { ch: '是', py: 'shì', mean: '~이다' },
      { ch: '有', py: 'yǒu', mean: '있다' },

      // --- 접속사 및 전치사 ---
      { ch: '如果', py: 'rúguǒ', mean: '만약' },
      { ch: '只要', py: 'zhǐyào', mean: '~하기만 하면' },
      { ch: '但是', py: 'dànshì', mean: '그러나, 하지만' },
      { ch: '可是', py: 'kěshì', mean: '그러나, 하지만' },
      { ch: '于是', py: 'yúshì', mean: '그래서' },
      { ch: '对', py: 'duì', mean: '맞다, ~에게' },
      { ch: '对于', py: 'duìyú', mean: '~에 대하여' },
      { ch: '为', py: 'wèi', mean: '~을 위하여' },
      { ch: '另外', py: 'lìngwài', mean: '그 밖에, 따로' },
      { ch: '一切', py: 'yíqiè', mean: '모든, 일체' },
      { ch: '最', py: 'zuì', mean: '가장, 제일' },
      { ch: '内容', py: 'nèiróng', mean: '내용' },
    ],
  },

  {
    id: 19,
    title: '19) 취미 및 여가활동',
    icon: '🎨',
    words: [
      // --- 취미 활동 ---
      { ch: '爱好', py: 'àihào', mean: '취미' },
      { ch: '玩儿', py: 'wánr', mean: '놀다, 즐기다' },
      { ch: '游戏', py: 'yóuxì', mean: '게임' },
      { ch: '唱歌', py: 'chàng gē', mean: '노래를 부르다' },
      { ch: '跳舞', py: 'tiào wǔ', mean: '춤을 추다' },
      { ch: '弹钢琴', py: 'tán gāngqín', mean: '피아노를 치다' },
      { ch: '画', py: 'huà', mean: '그리다, 그림' },
      { ch: '阅读', py: 'yuèdú', mean: '읽다, 독서하다' },
      { ch: '对…感兴趣', py: 'duì…gǎn xìngqù', mean: '~에 흥미가 있다' },

      // --- 미디어 및 기기 ---
      { ch: '音乐', py: 'yīnyuè', mean: '음악' },
      { ch: '电脑', py: 'diànnǎo', mean: '컴퓨터' },
      { ch: '电视', py: 'diànshì', mean: '텔레비전' },
      { ch: '上网', py: 'shàngwǎng', mean: '인터넷을 하다' },
      { ch: '互联网', py: 'hùliánwǎng', mean: '인터넷' },
      { ch: '网站', py: 'wǎngzhàn', mean: '웹사이트' },
      { ch: '照', py: 'zhào', mean: '찍다 (사진)' },
      { ch: '照片', py: 'zhàopiàn', mean: '사진' },
      { ch: '照相机', py: 'zhàoxiàngjī', mean: '사진기, 카메라' },

      // --- 책 및 단위 ---
      { ch: '杂志', py: 'zázhì', mean: '잡지' },
      { ch: '小说', py: 'xiǎoshuō', mean: '소설' },
      { ch: '篇', py: 'piān', mean: '(양사) 편, 장' },
      { ch: '页', py: 'yè', mean: '(양사) 페이지, 쪽' },
      { ch: '段', py: 'duàn', mean: '(양사) 단락, 마디' },
      { ch: '重点', py: 'zhòngdiǎn', mean: '중점' },

      // --- 추상적 개념 및 상태 ---
      { ch: '印象', py: 'yìnxiàng', mean: '인상' },
      { ch: '信心', py: 'xìnxīn', mean: '자신감' },
      { ch: '危险', py: 'wēixiǎn', mean: '위험하다' },
      { ch: '低', py: 'dī', mean: '낮다' },
      { ch: '光', py: 'guāng', mean: '빛, (보어) 다 ~해버리다' },
      { ch: '永远', py: 'yǒngyuǎn', mean: '영원히' },
      { ch: '许多', py: 'xǔduō', mean: '매우 많다' },

      // --- 동사 및 부사 ---
      { ch: '应该', py: 'yīnggāi', mean: '마땅히 ~해야 한다' },
      { ch: '提', py: 'tí', mean: '언급하다, 들다' },
      { ch: '提醒', py: 'tíxǐng', mean: '일깨우다, 주의를 주다' },
      { ch: '比如', py: 'bǐrú', mean: '예를 들면' },
      { ch: '例如', py: 'lìrú', mean: '예를 들면' },
      { ch: '最好', py: 'zuìhǎo', mean: '가장 좋다' },
      { ch: '其中', py: 'qízhōng', mean: '그 중에서' },
      { ch: '次', py: 'cì', mean: '(양사) 번, 회' },
      { ch: '等', py: 'děng', mean: '등등, 기타' },
    ],
  },

  {
    id: 20,
    title: '20) 운동하기',
    icon: '🏃',
    words: [
      // --- 운동 종류 및 동작 ---
      { ch: '运动', py: 'yùndòng', mean: '운동하다' },
      { ch: '跑步', py: 'pǎobù', mean: '달리다, 조깅하다' },
      { ch: '游泳', py: 'yóuyǒng', mean: '수영하다' },
      { ch: '爬山', py: 'pá shān', mean: '등산하다' },
      { ch: '散步', py: 'sànbù', mean: '산책하다' },
      { ch: '锻炼', py: 'duànliàn', mean: '단련하다, 운동하다' },
      { ch: '减肥', py: 'jiǎnféi', mean: '다이어트하다, 살을 빼다' },
      { ch: '活动', py: 'huódòng', mean: '활동하다, 움직이다' },
      { ch: '动作', py: 'dòngzuò', mean: '동작' },

      // --- 구기 종목 ---
      { ch: '踢足球', py: 'tī zúqiú', mean: '축구를 하다' },
      { ch: '打篮球', py: 'dǎ lánqiú', mean: '농구를 하다' },
      { ch: '打乒乓球', py: 'dǎ pīngpāngqiú', mean: '탁구를 하다' },
      { ch: '打网球', py: 'dǎ wǎngqiú', mean: '테니스를 하다' },
      { ch: '打羽毛球', py: 'dǎ yǔmáoqiú', mean: '배드민턴을 하다' },

      // --- 경기 및 결과 ---
      { ch: '比赛', py: 'bǐsài', mean: '시합, 경기' },
      { ch: '赢', py: 'yíng', mean: '이기다' },
      { ch: '输', py: 'shū', mean: '지다' },
      { ch: '获得', py: 'huòdé', mean: '획득하다, 얻다' },
      { ch: '第一', py: 'dìyī', mean: '1등, 제일' },
      { ch: '棒', py: 'bàng', mean: '대단하다, (능력이) 강하다' },
      { ch: '效果', py: 'xiàoguǒ', mean: '효과' },

      // --- 신체 상태 및 특징 ---
      { ch: '胖', py: 'pàng', mean: '뚱뚱하다' },
      { ch: '瘦', py: 'shòu', mean: '마르다' },
      { ch: '轻', py: 'qīng', mean: '가볍다' },
      { ch: '轻松', py: 'qīngsōng', mean: '홀가분하다, 편안하다' },
      { ch: '力气', py: 'lìqi', mean: '힘, 기운' },
      { ch: '汗', py: 'hàn', mean: '땀' },
      { ch: '习惯', py: 'xíguàn', mean: '습관' },
      { ch: '体育', py: 'tǐyù', mean: '체육, 스포츠' },
      { ch: '公园', py: 'gōngyuán', mean: '공원' },
      { ch: '公斤', py: 'gōngjīn', mean: '킬로그램 (kg)' },

      // --- 조동사 및 기타 동사 ---
      { ch: '会', py: 'huì', mean: '~할 줄 알다 (학습)' },
      { ch: '能', py: 'néng', mean: '~할 수 있다 (능력)' },
      { ch: '敢', py: 'gǎn', mean: '감히 ~하다, 용기 있다' },
      { ch: '进行', py: 'jìnxíng', mean: '진행하다' },
      { ch: '受到', py: 'shòudao', mean: '받다 (영향/사랑 등)' },
      { ch: '减少', py: 'jiǎnshǎo', mean: '줄이다, 감소하다' },
      { ch: '缺少', py: 'quēshǎo', mean: '부족하다' },

      // --- 부사 ---
      { ch: '特别', py: 'tèbié', mean: '특히' },
      { ch: '尤其', py: 'yóuqí', mean: '특히, 더욱이' },
    ],
  },

  {
    id: 21,
    title: '21) 여행지 날씨 & 기분',
    icon: '☀️',
    words: [
      // --- 날씨 및 기후 ---
      { ch: '天气', py: 'tiānqì', mean: '날씨' },
      { ch: '气候', py: 'qìhòu', mean: '기후' },
      { ch: '晴', py: 'qíng', mean: '맑다, 개다' },
      { ch: '阴', py: 'yīn', mean: '흐리다' },
      { ch: '下雨', py: 'xià yǔ', mean: '비가 오다' },
      { ch: '雪', py: 'xuě', mean: '눈' },
      { ch: '刮风', py: 'guā fēng', mean: '바람이 불다' },
      { ch: '空气', py: 'kōngqì', mean: '공기' },
      { ch: '下', py: 'xià', mean: '(비/눈이) 내리다' },

      // --- 기온 및 계절 ---
      { ch: '季节', py: 'jìjié', mean: '계절' },
      { ch: '春', py: 'chūn', mean: '봄' },
      { ch: '夏', py: 'xià', mean: '여름' },
      { ch: '秋', py: 'qiū', mean: '가을' },
      { ch: '冬', py: 'dōng', mean: '겨울' },
      { ch: '冷', py: 'lěng', mean: '춥다' },
      { ch: '热', py: 'rè', mean: '덥다' },
      { ch: '凉快', py: 'liángkuai', mean: '시원하다' },
      { ch: '暖和', py: 'nuǎnhuo', mean: '따뜻하다' },

      // --- 여행지 및 풍경 ---
      { ch: '景色', py: 'jǐngsè', mean: '경치, 풍경' },
      { ch: '美丽', py: 'měilì', mean: '아름답다' },
      { ch: '有名', py: 'yǒumíng', mean: '유명하다' },
      { ch: '城市', py: 'chéngshì', mean: '도시' },
      { ch: '郊区', py: 'jiāoqū', mean: '교외' },
      { ch: '民族', py: 'mínzú', mean: '민족' },
      { ch: '参观', py: 'cānguān', mean: '참관하다, 견학하다' },
      { ch: '提供', py: 'tígōng', mean: '제공하다' },
      { ch: '吸引', py: 'xīyǐn', mean: '매료시키다, 끌어당기다' },
      { ch: '到处', py: 'dàochù', mean: '곳곳, 도처' },

      // --- 감정 및 상태 ---
      { ch: '心情', py: 'xīnqíng', mean: '기분, 마음' },
      { ch: '压力', py: 'yālì', mean: '스트레스' },
      { ch: '放松', py: 'fàngsōng', mean: '긴장을 풀다' },
      { ch: '放心', py: 'fàng xīn', mean: '안심하다' },
      { ch: '丢', py: 'diū', mean: '잃어버리다' },
      { ch: '放', py: 'fàng', mean: '놓다' },
      { ch: '看见', py: 'kànjiàn', mean: '보이다, 보다' },

      // --- 부사 및 접속사 ---
      { ch: '多么', py: 'duōme', mean: '얼마나 (감탄)' },
      { ch: '一边', py: 'yìbiān', mean: '~하면서' },
      { ch: '竟然', py: 'jìngrán', mean: '뜻밖에도, 의외로' },
      { ch: '仍然', py: 'réngrán', mean: '여전히, 아직도' },
      { ch: '从来', py: 'cónglái', mean: '여태껏, 지금까지' },
    ],
  },
  {
    id: 22,
    title: '22) 병원 & 건강',
    icon: '🏥',
    words: [
      // --- 병원 및 의료진 ---
      { ch: '医院', py: 'yīyuàn', mean: '병원' },
      { ch: '医生', py: 'yīshēng', mean: '의사' },
      { ch: '大夫', py: 'dàifu', mean: '의사' },
      { ch: '护士', py: 'hùshi', mean: '간호사' },
      { ch: '打针', py: 'dǎ zhēn', mean: '주사를 맞다/놓다' },
      { ch: '药', py: 'yào', mean: '약' },
      { ch: '检查', py: 'jiǎnchá', mean: '검사하다' },

      // --- 증상 및 상태 ---
      { ch: '生病', py: 'shēng bìng', mean: '병이 나다' },
      { ch: '感冒', py: 'gǎnmào', mean: '감기, 감기 걸리다' },
      { ch: '发烧', py: 'fā shāo', mean: '열이 나다' },
      { ch: '咳嗽', py: 'késou', mean: '기침하다' },
      { ch: '疼', py: 'téng', mean: '아프다' },
      { ch: '严重', py: 'yánzhòng', mean: '심각하다' },
      { ch: '舒服', py: 'shūfu', mean: '편안하다, 몸이 좋다' },
      { ch: '难受', py: 'nánshòu', mean: '괴롭다, 몸이 안 좋다' },
      { ch: '受不了', py: 'shòu bu liǎo', mean: '참을 수 없다' },
      { ch: '死', py: 'sǐ', mean: '죽다, ~해 죽겠다' },
      { ch: '正常', py: 'zhèngcháng', mean: '정상적이다' },
      { ch: '健康', py: 'jiànkāng', mean: '건강하다' },

      // --- 신체 부위 ---
      { ch: '身体', py: 'shēntǐ', mean: '신체, 몸' },
      { ch: '脸', py: 'liǎn', mean: '얼굴' },
      { ch: '眼睛', py: 'yǎnjing', mean: '눈' },
      { ch: '耳朵', py: 'ěrduo', mean: '귀' },
      { ch: '鼻子', py: 'bízi', mean: '코' },
      { ch: '口', py: 'kǒu', mean: '입' },
      { ch: '肚子', py: 'dùzi', mean: '배' },
      { ch: '腿', py: 'tuǐ', mean: '다리' },
      { ch: '脚', py: 'jiǎo', mean: '발' },
      { ch: '胳膊', py: 'gēbo', mean: '팔' },
      { ch: '个子', py: 'gèzi', mean: '키, 신장' },

      // --- 생명 및 생활 ---
      { ch: '出生', py: 'chūshēng', mean: '태어나다' },
      { ch: '生命', py: 'shēngmìng', mean: '생명' },
      { ch: '生活', py: 'shēnghuó', mean: '생활하다, 삶' },
      { ch: '顺利', py: 'shùnlì', mean: '순조롭다' },

      // --- 기타 동사 및 표현 ---
      { ch: '告诉', py: 'gàosu', mean: '알리다, 말하다' },
      { ch: '知道', py: 'zhīdào', mean: '알다' },
      { ch: '引起', py: 'yǐnqǐ', mean: '야기하다, 일으키다' },
      { ch: '作用', py: 'zuòyòng', mean: '작용, 효과' },
      { ch: '原来', py: 'yuánlái', mean: '원래, 알고 보니' },
      { ch: '为什么', py: 'wèishénme', mean: '왜, 무엇 때문에' },
    ],
  },

  {
    id: 23,
    title: '23) 취업 및 직업',
    icon: '💼',
    words: [
      // --- 취업 과정 및 태도 ---
      { ch: '准备', py: 'zhǔnbèi', mean: '준비하다' },
      { ch: '努力', py: 'nǔlì', mean: '노력하다, 열심히 하다' },
      { ch: '认真', py: 'rènzhēn', mean: '성실하다, 진지하다' },
      { ch: '竞争', py: 'jìngzhēng', mean: '경쟁하다' },
      { ch: '招聘', py: 'zhāopìn', mean: '채용하다' },
      { ch: '应聘', py: 'yìngpìn', mean: '지원하다 (채용에 응하다)' },
      { ch: '坚持', py: 'jiānchí', mean: '견지하다, 버티다' },
      { ch: '放弃', py: 'fàngqì', mean: '포기하다' },
      { ch: '考虑', py: 'kǎolǜ', mean: '고려하다, 생각하다' },
      { ch: '决定', py: 'juédìng', mean: '결정하다' },
      { ch: '祝贺', py: 'zhùhè', mean: '축하하다' },
      { ch: '成功', py: 'chénggōng', mean: '성공하다' },

      // --- 직업 및 인물 ---
      { ch: '职业', py: 'zhíyè', mean: '직업' },
      { ch: '律师', py: 'lǜshī', mean: '변호사' },
      { ch: '教授', py: 'jiàoshòu', mean: '교수' },
      { ch: '警察', py: 'jǐngchá', mean: '경찰' },
      { ch: '记者', py: 'jìzhě', mean: '기자' },
      { ch: '作者', py: 'zuòzhě', mean: '저자' },
      { ch: '作家', py: 'zuòjiā', mean: '작가' },
      { ch: '演员', py: 'yǎnyuán', mean: '배우' },

      // --- 업무 및 조건 ---
      { ch: '工资', py: 'gōngzī', mean: '월급, 임금' },
      { ch: '收入', py: 'shōurù', mean: '수입, 소득' },
      { ch: '经验', py: 'jīngyàn', mean: '경험' },
      { ch: '经历', py: 'jīnglì', mean: '경력, 겪다' },
      { ch: '能力', py: 'nénglì', mean: '능력' },
      { ch: '机会', py: 'jīhuì', mean: '기회' },
      { ch: '通知', py: 'tōngzhī', mean: '통지하다, 알림' },
      { ch: '事情', py: 'shìqing', mean: '일, 사건' },
      { ch: '标准', py: 'biāozhǔn', mean: '기준, 표준' },
      { ch: '关键', py: 'guānjiàn', mean: '관건, 핵심' },
      { ch: '方面', py: 'fāngmiàn', mean: '방면, 분야' },
      { ch: '缺点', py: 'quēdiǎn', mean: '단점' },

      // --- 추상적 개념 및 기타 ---
      { ch: '希望', py: 'xīwàng', mean: '희망하다' },
      { ch: '理想', py: 'lǐxiǎng', mean: '이상, 꿈' },
      { ch: '梦', py: 'mèng', mean: '꿈' },
      { ch: '成为', py: 'chéngwéi', mean: '~이 되다' },
      { ch: '重要', py: 'zhòngyào', mean: '중요하다' },
      { ch: '自己', py: 'zìjǐ', mean: '자기, 자신' },
      { ch: '终于', py: 'zhōngyú', mean: '마침내, 드디어' },
      { ch: '完', py: 'wán', mean: '끝내다, 마치다' },
    ],
  },

  {
    id: 24,
    title: '24) 회사 업무 1',
    icon: '🏢',
    words: [
      // --- 근무 및 근태 ---
      { ch: '工作', py: 'gōngzuò', mean: '일하다, 업무' },
      { ch: '上班', py: 'shàngbān', mean: '출근하다' },
      { ch: '下班', py: 'xiàbān', mean: '퇴근하다' },
      { ch: '加班', py: 'jiābān', mean: '야근하다, 특근하다' },
      { ch: '出差', py: 'chūchāi', mean: '출장 가다' },
      { ch: '休息', py: 'xiūxi', mean: '휴식하다, 쉬다' },
      { ch: '请假', py: 'qǐng jià', mean: '휴가를 신청하다' },
      { ch: '迟到', py: 'chídào', mean: '지각하다' }, // 문맥상 자주 쓰여서 추가(선택)
      { ch: '忙', py: 'máng', mean: '바쁘다' },
      { ch: '累', py: 'lèi', mean: '피곤하다' },

      // --- 직위 및 인물 ---
      { ch: '公司', py: 'gōngsī', mean: '회사' },
      { ch: '同事', py: 'tóngshì', mean: '동료' },
      { ch: '经理', py: 'jīnglǐ', mean: '매니저, 지배인' },
      { ch: '老板', py: 'lǎobǎn', mean: '사장' },

      // --- 업무 처리 및 소통 ---
      { ch: '开会', py: 'kāihuì', mean: '회의하다' }, // 회의(명사) 외에 동사형도 자주 쓰임
      { ch: '会议', py: 'huìyì', mean: '회의' },
      { ch: '参加', py: 'cānjiā', mean: '참가하다' },
      { ch: '商量', py: 'shāngliang', mean: '상의하다, 의논하다' },
      { ch: '意见', py: 'yìjiàn', mean: '의견' },
      { ch: '安排', py: 'ānpái', mean: '안배하다, 처리하다' },
      { ch: '负责', py: 'fùzé', mean: '책임지다, 맡다' },
      { ch: '责任', py: 'zérèn', mean: '책임' },
      { ch: '完成', py: 'wánchéng', mean: '완성하다, 끝내다' },
      { ch: '干', py: 'gàn', mean: '하다, 일하다' },
      { ch: '当', py: 'dāng', mean: '~이 되다, 맡다' },
      { ch: '陪', py: 'péi', mean: '동반하다, 모시다' },
      { ch: '适应', py: 'shìyìng', mean: '적응하다' },

      // --- 사무실 및 문서 ---
      { ch: '办公室', py: 'bàngōngshì', mean: '사무실' },
      { ch: '打印', py: 'dǎyìn', mean: '인쇄하다, 프린트하다' },
      { ch: '复印', py: 'fùyìn', mean: '복사하다' },
      { ch: '传真', py: 'chuánzhēn', mean: '팩스' },
      { ch: '计划', py: 'jìhuà', mean: '계획, 기획하다' },
      { ch: '材料', py: 'cáiliào', mean: '자료' },
      { ch: '表格', py: 'biǎogé', mean: '표, 서식' },
      { ch: '份', py: 'fèn', mean: '(양사) 부, 통 (서류)' },
      { ch: '总结', py: 'zǒngjié', mean: '총결산하다, 정리하다' },
      { ch: '管理', py: 'guǎnlǐ', mean: '관리하다' },

      // --- 기타 ---
      { ch: '结果', py: 'jiéguǒ', mean: '결과' },
      { ch: '目的', py: 'mùdì', mean: '목적' },
      { ch: '任务', py: 'rènwu', mean: '임무' },
      { ch: '主意', py: 'zhǔyi', mean: '아이디어, 생각' },
      { ch: '专门', py: 'zhuānmén', mean: '전문적으로, 특별히' },
      { ch: '顺便', py: 'shùnbiàn', mean: '~하는 김에, 겸사겸사' },
      { ch: '赚', py: 'zhuàn', mean: '돈을 벌다' },
      { ch: '抽烟', py: 'chōu yān', mean: '담배를 피우다' },
    ],
  },

  {
    id: 25,
    title: '25) 회사 업무 2 (은행/우체국)',
    icon: '🏦',
    words: [
      // --- 우체국 및 은행 업무 ---
      { ch: '邮局', py: 'yóujú', mean: '우체국' },
      { ch: '寄', py: 'jì', mean: '보내다, 부치다' },
      { ch: '信封', py: 'xìnfēng', mean: '편지 봉투' },
      { ch: '银行', py: 'yínháng', mean: '은행' },
      { ch: '取', py: 'qǔ', mean: '찾다, 출금하다' },
      { ch: '存', py: 'cún', mean: '저금하다, 보관하다' },
      { ch: '排队', py: 'pái duì', mean: '줄을 서다' },
      { ch: '收', py: 'shōu', mean: '받다, 거두다' },
      { ch: '拿', py: 'ná', mean: '쥐다, 들다, 가지다' },

      // --- 화폐 및 경제 ---
      { ch: '现金', py: 'xiànjīn', mean: '현금' },
      { ch: '零钱', py: 'língqián', mean: '잔돈' },
      { ch: '信用卡', py: 'xìnyòngkǎ', mean: '신용카드' },
      { ch: '元', py: 'yuán', mean: '위안 (화폐 단위)' },
      { ch: '毛', py: 'máo', mean: '마오 (화폐 단위)' },
      { ch: '经济', py: 'jīngjì', mean: '경제' },
      { ch: '倍', py: 'bèi', mean: '배, 곱절' },
      { ch: '百分之', py: 'bǎifēnzhī', mean: '퍼센트, 백분의...' },

      // --- 업무 상황 및 논리 ---
      { ch: '情况', py: 'qíngkuàng', mean: '상황' },
      { ch: '要求', py: 'yāoqiú', mean: '요구하다, 요구' },
      { ch: '判断', py: 'pànduàn', mean: '판단하다' },
      { ch: '了解', py: 'liǎojiě', mean: '잘 알다, 이해하다' },
      { ch: '保证', py: 'bǎozhèng', mean: '보증하다' },
      { ch: '超过', py: 'chāoguò', mean: '초과하다, 넘다' },
      { ch: '简单', py: 'jiǎndān', mean: '간단하다' },
      { ch: '主要', py: 'zhǔyào', mean: '주요한, 주로' },
      { ch: '故意', py: 'gùyì', mean: '고의로, 일부러' },
      { ch: '到底', py: 'dàodǐ', mean: '도대체, 마침내' },
      { ch: '排列', py: 'páiliè', mean: '나열하다, 배열하다' },
      { ch: '座位', py: 'zuòwèi', mean: '좌석' },

      // --- 접속사 및 문법 ---
      { ch: '因为', py: 'yīnwèi', mean: '왜냐하면, ~때문에' },
      { ch: '所以', py: 'suǒyǐ', mean: '그래서' },
      { ch: '由于', py: 'yóuyú', mean: '~때문에 (원인)' },
      { ch: '不但', py: 'búdàn', mean: '~뿐만 아니라' },
      { ch: '而且', py: 'érqiě', mean: '게다가' },
      { ch: '只有', py: 'zhǐyǒu', mean: '오직 ~해야만' },
      { ch: '才', py: 'cái', mean: '비로소' },
      { ch: '否则', py: 'fǒuzé', mean: '그렇지 않으면' },
      { ch: '得', py: 'děi / dé', mean: '~해야 한다 / 얻다' }, // 두 가지 발음/뜻 모두 표기
      { ch: '首先', py: 'shǒuxiān', mean: '먼저, 우선' },

      // --- 인물 ---
      { ch: '小伙子', py: 'xiǎohuǒzi', mean: '젊은이, 총각' },
    ],
  },

  {
    id: 26,
    title: '26) 회의 및 미팅',
    icon: '🗓️',
    words: [
      // --- 시간 및 일정 관리 ---
      { ch: '按时', py: 'ànshí', mean: '제때에, 시간에 맞춰' },
      { ch: '准时', py: 'zhǔnshí', mean: '정시에, 제때에' },
      { ch: '平时', py: 'píngshí', mean: '평소, 평상시' },
      { ch: '提前', py: 'tíqián', mean: '앞당기다' },
      { ch: '推迟', py: 'tuīchí', mean: '미루다, 연기하다' },
      { ch: '将来', py: 'jiānglái', mean: '미래, 장래' },
      { ch: '后来', py: 'hòulái', mean: '그 뒤, 그 후' },
      { ch: '刚', py: 'gāng', mean: '방금, 막' },
      { ch: '同时', py: 'tóngshí', mean: '동시에' },
      { ch: '大约', py: 'dàyuē', mean: '대략, 아마' },
      { ch: '偶尔', py: "ǒu'ěr", mean: '가끔, 때때로' },
      { ch: '来得及', py: 'lái de jí', mean: '늦지 않다, 시간 있다' },
      { ch: '来不及', py: 'lái bu jí', mean: '늦다, 시간 없다' },

      // --- 진행 및 상황 ---
      { ch: '邀请', py: 'yāoqǐng', mean: '초대하다' },
      { ch: '直接', py: 'zhíjiē', mean: '직접적인' },
      { ch: '改变', py: 'gǎibiàn', mean: '바꾸다, 변하다' },
      { ch: '降低', py: 'jiàngdī', mean: '낮추다' },
      { ch: '值得', py: 'zhíde', mean: '~할 가치가 있다' },
      { ch: '接', py: 'jiē', mean: '받다, 마중하다' },
      { ch: '使', py: 'shǐ', mean: '~하게 하다, 시키다' },
      { ch: '原谅', py: 'yuánliàng', mean: '양해하다, 용서하다' },
      { ch: '区别', py: 'qūbié', mean: '구별, 차이' },
      { ch: '部分', py: 'bùfen', mean: '부분' },
      { ch: '地点', py: 'dìdiǎn', mean: '장소, 지점' },
      { ch: '样子', py: 'yàngzi', mean: '모양, 모습' },
      { ch: '正式', py: 'zhèngshì', mean: '정식의, 공식적인' },

      // --- 논리 및 부사/접속사 ---
      { ch: '原因', py: 'yuányīn', mean: '원인' },
      { ch: '差不多', py: 'chàbuduō', mean: '거의, 비슷하다' },
      { ch: '随便', py: 'suíbiàn', mean: '마음대로' },
      { ch: '突然', py: 'tūrán', mean: '갑자기' },
      { ch: '难道', py: 'nándào', mean: '설마 ~란 말인가?' },
      { ch: '即使', py: 'jíshǐ', mean: '설령 ~하더라도' },
      { ch: '究竟', py: 'jiūjìng', mean: '도대체' },
      { ch: '甚至', py: 'shènzhì', mean: '심지어, ~조차도' },
      { ch: '至少', py: 'zhìshǎo', mean: '적어도' },
      { ch: '连', py: 'lián', mean: '~조차도, 연결하다' }, // 뜻 수정됨
      { ch: '不得不', py: 'bùdébù', mean: '어쩔 수 없이 ~해야 한다' },
      { ch: '只好', py: 'zhǐhǎo', mean: '부득이, 할 수 없이' },
      { ch: '恐怕', py: 'kǒngpà', mean: '아마 ~일 것이다 (우려)' },
      { ch: '也许', py: 'yěxǔ', mean: '아마도, 어쩌면' },

      // --- 기타 ---
      { ch: '场', py: 'chǎng', mean: '(양사) 차례, 회' },
    ],
  },

  {
    id: 27,
    title: '27) 수업 및 학교생활',
    icon: '🏫',
    words: [
      // --- 학교 및 장소 ---
      { ch: '学校', py: 'xuéxiào', mean: '학교' },
      { ch: '教室', py: 'jiàoshì', mean: '교실' },
      { ch: '图书馆', py: 'túshūguǎn', mean: '도서관' }, // 13과 복습 겸 맥락상 추가
      { ch: '班', py: 'bān', mean: '반, 학급' },
      { ch: '年级', py: 'niánjí', mean: '학년' },

      // --- 사람 ---
      { ch: '老师', py: 'lǎoshī', mean: '선생님' },
      { ch: '学生', py: 'xuésheng', mean: '학생' },
      { ch: '同学', py: 'tóngxué', mean: '학우, 반 친구' },
      { ch: '朋友', py: 'péngyou', mean: '친구' },
      { ch: '校长', py: 'xiàozhǎng', mean: '교장 선생님' },

      // --- 수업 도구 ---
      { ch: '书', py: 'shū', mean: '책' },
      { ch: '本', py: 'běn', mean: '(양사) 권 (책 세는 단위)' },
      { ch: '词典', py: 'cídiǎn', mean: '사전' },
      { ch: '黑板', py: 'hēibǎn', mean: '칠판' },
      { ch: '铅笔', py: 'qiānbǐ', mean: '연필' },
      { ch: '橡皮', py: 'xiàngpí', mean: '지우개' },
      { ch: '椅子', py: 'yǐzi', mean: '의자' },

      // --- 학습 내용 ---
      { ch: '汉语', py: 'Hànyǔ', mean: '중국어' },
      { ch: '历史', py: 'lìshǐ', mean: '역사' },
      { ch: '数学', py: 'shùxué', mean: '수학' },
      { ch: '专业', py: 'zhuānyè', mean: '전공' },
      { ch: '课', py: 'kè', mean: '수업, 강의' },
      { ch: '学期', py: 'xuéqī', mean: '학기' },
      { ch: '字', py: 'zì', mean: '글자' },
      { ch: '句子', py: 'jùzi', mean: '문장' },
      { ch: '文章', py: 'wénzhāng', mean: '글, 문장' },
      { ch: '题', py: 'tí', mean: '문제, 제목' },

      // --- 동작 ---
      { ch: '读', py: 'dú', mean: '읽다, 공부하다' },
      { ch: '写', py: 'xiě', mean: '쓰다' },
      { ch: '教', py: 'jiāo', mean: '가르치다' },
      { ch: '教育', py: 'jiàoyù', mean: '교육하다, 교육' },
      { ch: '讲', py: 'jiǎng', mean: '말하다, 강의하다' },
      { ch: '复习', py: 'fùxí', mean: '복습하다' },
      { ch: '考试', py: 'kǎoshì', mean: '시험보다' },
      { ch: '报名', py: 'bàomíng', mean: '등록하다, 신청하다' },
      { ch: '解决', py: 'jiějué', mean: '해결하다, 풀다' },
      { ch: '结束', py: 'jiéshù', mean: '끝나다' },
      { ch: '记得', py: 'jìde', mean: '기억하다' },
      { ch: '支持', py: 'zhīchí', mean: '지지하다, 버티다' },
      { ch: '上', py: 'shàng', mean: '위, (수업을) 하다/가다' },

      // --- 접속사 ---
      { ch: '虽然', py: 'suīrán', mean: '비록 ~하지만' },
    ],
  },
  {
    id: 28,
    title: '28) 대중매체 및 문화',
    icon: '📺',
    words: [
      // --- 공연 및 예술 ---
      { ch: '表演', py: 'biǎoyǎn', mean: '공연하다, 연기' },
      { ch: '演出', py: 'yǎnchū', mean: '공연, 공연하다' },
      { ch: '京剧', py: 'jīngjù', mean: '경극' },
      { ch: '艺术', py: 'yìshù', mean: '예술' },
      { ch: '观众', py: 'guānzhòng', mean: '관중, 시청자' },
      { ch: '声音', py: 'shēngyīn', mean: '목소리, 소리' },
      { ch: '看', py: 'kàn', mean: '보다' },
      { ch: '笑', py: 'xiào', mean: '웃다' },

      // --- 방송 및 매체 ---
      { ch: '节目', py: 'jiémù', mean: '프로그램' },
      { ch: '新闻', py: 'xīnwén', mean: '뉴스' },
      { ch: '报纸', py: 'bàozhǐ', mean: '신문' },
      { ch: '广播', py: 'guǎngbō', mean: '방송, 방송하다' },
      { ch: '广告', py: 'guǎnggào', mean: '광고' },
      { ch: '信息', py: 'xìnxī', mean: '정보' },
      { ch: '消息', py: 'xiāoxi', mean: '소식' },
      { ch: '故事', py: 'gùshi', mean: '이야기' },
      { ch: '笑话', py: 'xiàohua', mean: '농담' },

      // --- 행사 및 상태 ---
      { ch: '举行', py: 'jǔxíng', mean: '개최하다 (행사)' },
      { ch: '举办', py: 'jǔbàn', mean: '개최하다 (주최)' },
      { ch: '火', py: 'huǒ', mean: '인기 있다, 핫하다' },
      { ch: '著名', py: 'zhùmíng', mean: '유명하다' },
      { ch: '普遍', py: 'pǔbiàn', mean: '보편적이다' },
      { ch: '丰富', py: 'fēngfù', mean: '풍부하다' },
      { ch: '够', py: 'gòu', mean: '충분하다' },
      { ch: '厚', py: 'hòu', mean: '두껍다' },
      { ch: '老', py: 'lǎo', mean: '오래된, 늙은' },
      { ch: '错', py: 'cuò', mean: '틀리다, 잘못하다' },
      { ch: '一样', py: 'yíyàng', mean: '같다' },

      // --- 부사 및 접속사 ---
      { ch: '其实', py: 'qíshí', mean: '사실, 실은' },
      { ch: '实在', py: 'shízài', mean: '정말, 성실하다' },
      { ch: '千万', py: 'qiānwàn', mean: '제발, 절대로' },
      { ch: '一共', py: 'yígòng', mean: '모두, 합계' },
      { ch: '接着', py: 'jiēzhe', mean: '이어서, 연이어' },
      { ch: '当时', py: 'dāngshí', mean: '당시, 그때' },
      { ch: '最后', py: 'zuìhòu', mean: '마지막' },
      { ch: '中间', py: 'zhōngjiān', mean: '중간' },
      { ch: '意思', py: 'yìsi', mean: '의미, 재미' },

      // --- 조사 및 기타 ---
      { ch: '外', py: 'wài', mean: '밖, 이외' },
      { ch: '了', py: 'le', mean: '~했다 (완료/변화)' },
      { ch: '啊', py: 'a', mean: '(감탄/의문 조사)' },
    ],
  },

  {
    id: 29,
    title: '29) 시사 및 사회 문제',
    icon: '📰',
    words: [
      // --- 연구 및 조사 ---
      { ch: '研究', py: 'yánjiū', mean: '연구하다' },
      { ch: '科学', py: 'kēxué', mean: '과학' },
      { ch: '技术', py: 'jìshù', mean: '기술' },
      { ch: '调查', py: 'diàochá', mean: '조사하다' },
      { ch: '发现', py: 'fāxiàn', mean: '발견하다' },
      { ch: '说明', py: 'shuōmíng', mean: '설명하다' },
      { ch: '解释', py: 'jiěshì', mean: '해석하다, 설명하다' },
      { ch: '回答', py: 'huídá', mean: '대답하다' },
      { ch: '指', py: 'zhǐ', mean: '가리키다, 지적하다' },

      // --- 사회 및 법률 ---
      { ch: '社会', py: 'shèhuì', mean: '사회' },
      { ch: '法律', py: 'fǎlǜ', mean: '법률' },
      { ch: '禁止', py: 'jìnzhǐ', mean: '금지하다' },
      { ch: '亚洲', py: 'Yàzhōu', mean: '아시아' },
      { ch: '发展', py: 'fāzhǎn', mean: '발전하다' },
      { ch: '变化', py: 'biànhuà', mean: '변화하다' },
      { ch: '影响', py: 'yǐngxiǎng', mean: '영향, 영향을 주다' },
      { ch: '富', py: 'fù', mean: '부유하다' },
      { ch: '穷', py: 'qióng', mean: '가난하다, 빈곤하다' },

      // --- 자원 및 태도 ---
      { ch: '浪费', py: 'làngfèi', mean: '낭비하다' },
      { ch: '节约', py: 'jiéyuē', mean: '절약하다' },
      { ch: '节', py: 'jié', mean: '아끼다, 명절' },
      { ch: '省', py: 'shěng', mean: '아끼다, 성(행정구역)' },
      { ch: '留', py: 'liú', mean: '남기다' },
      { ch: '明白', py: 'míngbai', mean: '이해하다, 명백하다' },
      { ch: '清楚', py: 'qīngchu', mean: '분명하다, 맑다' },
      { ch: '准确', py: 'zhǔnquè', mean: '정확하다' },
      { ch: '方法', py: 'fāngfǎ', mean: '방법' },

      // --- 전치사 및 접속사 (논리) ---
      { ch: '随着', py: 'suízhe', mean: '~에 따라' },
      { ch: '按照', py: 'ànzhào', mean: '~에 따라 (기준)' },
      { ch: '关于', py: 'guānyú', mean: '~에 관하여 (범위)' },
      { ch: '对于', py: 'duìyú', mean: '~에 대하여 (대상)' },
      { ch: '以', py: 'yǐ', mean: '~로써, ~을 가지고' },
      { ch: '既然', py: 'jìrán', mean: '~인 이상, 기왕 ~한 바에야' },
      { ch: '越', py: 'yuè', mean: '점점, ~할수록' },
      { ch: '还是', py: 'háishi', mean: '아직도, 여전히, 또는' },

      // --- 부사 및 기타 ---
      { ch: '本来', py: 'běnlái', mean: '원래, 본래 (당연함)' },
      { ch: '原来', py: 'yuánlái', mean: '알고 보니, 원래 (발견)' },
      { ch: '大概', py: 'dàgài', mean: '대략, 아마도 (상황/수량)' },
      { ch: '大约', py: 'dàyuē', mean: '대략 (수량)' },
      { ch: '暂时', py: 'zànshí', mean: '잠시, 일시적으로' },
      { ch: '内', py: 'nèi', mean: '안, 내부' },
      { ch: '底', py: 'dǐ', mean: '밑, 바닥, 말(시기)' },
      { ch: '遍', py: 'biàn', mean: '(양사) 번, 회 (처음부터 끝까지)' },
      { ch: '个', py: 'gè', mean: '(양사) 개, 명' },
    ],
  },

  {
    id: 30,
    title: '30) 자연 및 환경',
    icon: '🌳',
    words: [
      // --- 자연 요소 ---
      { ch: '自然', py: 'zìrán', mean: '자연' },
      { ch: '环境', py: 'huánjìng', mean: '환경' },
      { ch: '地球', py: 'dìqiú', mean: '지구' },
      { ch: '海洋', py: 'hǎiyáng', mean: '바다, 해양' },
      { ch: '森林', py: 'sēnlín', mean: '숲, 삼림' },
      { ch: '太阳', py: 'tàiyáng', mean: '태양, 해' },
      { ch: '阳光', py: 'yángguāng', mean: '햇빛' },
      { ch: '月亮', py: 'yuèliang', mean: '달' },
      { ch: '云', py: 'yún', mean: '구름' },
      { ch: '温度', py: 'wēndù', mean: '온도' },

      // --- 동물 ---
      { ch: '动物', py: 'dòngwù', mean: '동물' },
      { ch: '熊猫', py: 'xióngmāo', mean: '판다' },
      { ch: '老虎', py: 'lǎohǔ', mean: '호랑이' },
      { ch: '马', py: 'mǎ', mean: '말' },
      { ch: '猫', py: 'māo', mean: '고양이' },
      { ch: '狗', py: 'gǒu', mean: '개' }, // 뜻 수정됨
      { ch: '鸟', py: 'niǎo', mean: '새' },
      { ch: '只', py: 'zhī', mean: '(양사) 마리' },

      // --- 식물 ---
      { ch: '植物', py: 'zhíwù', mean: '식물' },
      { ch: '树', py: 'shù', mean: '나무' },
      { ch: '草', py: 'cǎo', mean: '풀' },
      { ch: '叶子', py: 'yèzi', mean: '잎, 잎사귀' },
      { ch: '绿', py: 'lǜ', mean: '초록색, 푸르다' },
      { ch: '棵', py: 'kē', mean: '(양사) 그루' },

      // --- 환경 보호 및 추상적 개념 ---
      { ch: '保护', py: 'bǎohù', mean: '보호하다' },
      { ch: '爱护', py: 'àihù', mean: '아끼고 보호하다' },
      { ch: '污染', py: 'wūrǎn', mean: '오염, 오염시키다' },
      { ch: '世纪', py: 'shìjì', mean: '세기 (100년)' },
      { ch: '建议', py: 'jiànyì', mean: '제안하다, 건의하다' },
      { ch: '表示', py: 'biǎoshì', mean: '표시하다, 나타내다' },
      { ch: '表达', py: 'biǎodá', mean: '표현하다' },
      { ch: '感觉', py: 'gǎnjué', mean: '느끼다, 감각' },
      { ch: '伤心', py: 'shāngxīn', mean: '상심하다, 슬프다' },
      { ch: '掉', py: 'diào', mean: '떨어지다, 빠지다' },
      { ch: '顺序', py: 'shùnxù', mean: '순서' },

      // --- 사물 및 사람 ---
      { ch: '桥', py: 'qiáo', mean: '다리' },
      { ch: '座', py: 'zuò', mean: '(양사) 동, 채, 좌' },
      { ch: '嘴', py: 'zuǐ', mean: '입' },
      { ch: '入口', py: 'rùkǒu', mean: '입구' },
      { ch: '儿童', py: 'értóng', mean: '어린이, 아동' },

      // --- 문법 (전치사/접속사) ---
      { ch: '为了', py: 'wèi le', mean: '~하기 위하여 (목적)' },
      { ch: '为', py: 'wèi', mean: '~를 위하여, ~때문에' },
      { ch: '尽管', py: 'jǐnguǎn', mean: '비록 ~일지라도' },
    ],
  },
];
